### ISSUE TITLE
Any plan to support dmaker.fan.p9?

### ISSUE THREAD

**Issue by elliana-wt** [merdok/homebridge-xiaomi-fan#10]
I bought a MIJIA Tower Fan yesterday, but this plug-in doesn't support this device. This model name is dmaker.fan.p9. Is there any plan to support it?

**Comment by merdok** [comment]
Unfortunately i do not have this fan, so i cannot easily add support for it. First we would need to make sure if the miio library supports that device. Could you post here the debug log from homebridge when trying to connect to the fan?

**Comment by elliana-wt** [comment]
Yep. when I using the Homebridge -D, it show this:

```
[6/24/2020, 18:05:12] [TowerFan] Initializing xiaomifan accessory...
```
......
```
[6/24/2020, 18:05:22] [TowerFan] Xiaomi Fan - found Fan in network. Trying to connect...
[6/24/2020, 18:05:22] [TowerFan] Xiaomi Fan - connected to Fan
[6/24/2020, 18:05:22] [TowerFan] MiioDevice {
  model=dmaker.fan.p9,
  types=miio,
  capabilities=
}
[6/24/2020, 18:05:22] [TowerFan] Xiaomi Fan - fan model info file already exists, not saving!
Killed
```

**Comment by elliana-wt** [comment]
Also, when I running the `miio discover`, it can find the fan, but the Model info is showing 'unknow'.

```
cheukfaiho@MacBookPro ~ % npm install -g miio
/usr/local/bin/miio -> /usr/local/lib/node_modules/miio/cli/index.js
+ miio@0.15.6
added 114 packages from 53 contributors in 3.663s
cheukfaiho@MacBookPro ~ % miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 242845998
Model info: Unknown
Address: 192.168.1.237
Token: ???
Support: Unknown
```

**Comment by merdok** [comment]
Yeah, it seems that the dmaker fans have a slightly different api. I will see what i can do about it.

**Comment by merdok** [comment]
Version 0.9.2 should now have initial dmaker fan support. Could you try it out and also post your debug log after connecting to the fan?

**Comment by merdok** [comment]
If you want me to add support for your fan then you would need to dump the commands from your fan. Would you willing to do that?

**Comment by elliana-wt** [comment]
> Version 0.9.2 should now have initial dmaker fan support. Could you try it out and also post your debug log after connecting to the fan?

Sorry for the late reply, I went on a trip during the Dragon Boat Festival. I will try it after work today.

**Comment by elliana-wt** [comment]
> If you want me to add support for your fan then you would need to dump the commands from your fan. Would you willing to do that?

Of course, just tell me how to do that. (I am not a pro programmer)

**Comment by merdok** [comment]
It requires a a couple of steps to be done. You can basically read here how to dump commands from your device:
https://github.com/aholstenson/miio/blob/master/docs/protocol.md
https://github.com/jghaanstra/com.robot.xiaomi-mi

Someone already tried that in a different issues without success but you could anyway try out also since Maxine it could work for you...

**Comment by sw2719** [comment]
Could you try to log the commands with modded mi home app?  [Follow this gude.](https://gist.github.com/sw2719/fe7820e1913fc876f9011700b31ae625)

**Comment by merdok** [comment]
@CheukFaiho version 1.3.0 should add support for the dmaker.fan.p9. Can you try it out please?
