### ISSUE TITLE
dmaker.fan.p18 (Xiaomi Mi Smart Standing Fan 2) seems compatible

### ISSUE THREAD

**Issue by Andiweli** [merdok/homebridge-xiaomi-fan#100]
Perhaps you want to update your compatibility list.
I was able to integrate two "Xiaomi Mi Smart Standing Fan 2" into my Apple Home.

Device type is "dmaker.fan.p18" (Xiaomi Mi Smart Standing Fan 2, Model XM220004).

Regards

**Comment by merdok** [comment]
What device did you enter in the model  property to make the dmaker.dan.p18 work?

**Comment by merdok** [comment]
The dmaker.fan.p18 is now supported since version 1.5.5
