### ISSUE TITLE
Plugin functions not working except on/off

### ISSUE THREAD

**Issue by Andiweli** [merdok/homebridge-xiaomi-fan#101]
Hello!

First of all, I am using your plugin in ioBroker with iobroker.ham wrapper.

I have two dmaker.fan.p18 (Standing Fan 2) and one zhimi.fan.za4 (Standing Fan 2S).
All of them can be found with IP and tokencode - and I can switch all of them on and off with the "Active" flag (see screenshot).

![Bildschirmfoto 2021-07-12 um 17 37 08](https://user-images.githubusercontent.com/11447150/125316221-344bf900-e338-11eb-94ba-3214ce19eeb1.png)

But it is strange, that none of the other flags will trigger something.
For example if I set "Rotation-Direction" or "Rotation-Speed", for a few seconds the value is shown in the objects-tree, but after a few seconds it gets back to zero and nothing happens at the fan.

I tried with all the settings, so far I only can get "Active" working.
So for the "special" settings like Oscillation, Natural/Standard wind, Swing mode, Speed modes and buzzer/LEDs I have to use the Xiaomi app so far.

Also using the Xiaomi app, the following values won‘t change in the objects list for the dmaker.fan.p18 (but do for the .zh4):

- LED - stays false
- Natural-mode - stays false
- Firware shows 1.5.3 but is 2.0.7 in Xiaomi app
- There are also no „Angle“ objects

Is this some common problem and has it to be solved with some tricks?
Or did I get something wrong?

PS: I can switch the Fans on/off via Home App and they use the mode and speed I switched them off before (which I set via Xiaomi app) so the speed/fanstate seems to be saved, which is no problem for me so far using it that way. It just would it make more comfortable, to have those "special settings" also in the Home app :)

Thanks!

**Comment by merdok** [comment]
The dmaker.fan.p18 is not officially supported so that will cause your issues. That you can turn it on/off is just pure luck since maybe that property is exactly the same as with the fan model which you used to make it work. So my question is, what did you enter in the model property for the dmaker.fan.p18 fan?

**Comment by Andiweli** [comment]
I entered "dmaker.fan.p18" 😵 As shown in the app "Get Mi home device token".

Din't know this is bound also to the functionalities.

**Comment by merdok** [comment]
If you entered dmaker.fan.p18 then the fan is not detected and it defaults to the generic one... I see that the dmaker.fan.p10 is basically the same fan so if you enter that model it should work. I will add proper support in the next update.

**Comment by Andiweli** [comment]
I tried dmaker.fan.p10 (and zhimi.fan.za3 too) now,** it now shows all missing objects like left/right and the angles.
But when changing the values in the MiHome app, most of the values in the objects won't change - except the "Level 1 - 4" objects which change to true now.

Natural-mode, LED, move-left and move-right stay still stay "false" all the time even if I change something in the MiHome app.

**Comment by andiweli** [comment]
> I tried dmaker.fan.p10 now, it now shows all missing objects like left/right and the angles.
> But when changing the values in the MiHome app, most of the values in the objects won't change - except the "Level 1 - 4" objects which change to true now.
> 
> Natural-mode, LED, move-left and move-right stay still stay "false" all the time even if I change something in the MiHome app.

**Comment by Andiweli** [comment]
Thanks for adding the dmaker.fan.p18 to the compatibility list.
Sadly the values for the following variables still stay "false" no matter what I change in the MiHome app:

- Buzzer
- LED
- Natural-mode
- Angle--30 to Angle--140 (they even wont show now, but did with .p10 enabled - but still stays "false" with .p10)

All those values are working on my zhimi.fan.za4.

Here's my config in addition (I blanked the tokens)...

{
    "platform": "xiaomifan",
    "devices": [
        {
            "name": "SmartMi Fan 2S Schlafen",
            "ip": "10.0.0.249",
            "model": "zhimi.fan.za4",
            "token": "xxx",
            "pollingInterval": 10,
            "moveControl": true,
            "buzzerControl": true,
            "ledControl": true,
            "naturalModeControl": true,
            "shutdownTimer": true,
            "angleButtons": [
                30,
                60,
                90,
                120
            ]
        },
        {
            "name": "SmartMi Fan 2 Büro",
            "ip": "10.0.0.160",
            "model": "dmaker.fan.p18",
            "token": "xxx",
            "pollingInterval": 10,
            "moveControl": true,
            "buzzerControl": true,
            "ledControl": true,
            "naturalModeControl": true,
            "shutdownTimer": true,
            "angleButtons": [
                30,
                60,
                90,
                120,
                140
            ]
        },
        {
            "name": "SmartMi Fan 2 Lukas",
            "ip": "10.0.0.178",
            "model": "dmaker.fan.p18",
            "token": "xxx",
            "pollingInterval": 10,
            "moveControl": true,
            "buzzerControl": true,
            "ledControl": true,
            "naturalModeControl": true,
            "shutdownTimer": true,
            "angleButtons": [
                30,
                60,
                90,
                120,
                140
            ]
        }
    ]
}

**Comment by merdok** [comment]
You can post some homebridge debug log to so we can have a look if there are any errors.

**Comment by Andiweli** [comment]
> You can post some homebridge debug log to so we can have a look if there are any errors.

I've now enabled the "deepDebug" flag for one of the two .p18 fans.
Where can I find the logfile?

**Comment by merdok** [comment]
deepDebugLog itself will bring nothing, for it to work you need to start homebridge in debug mode and watch/copy the terminal content.

**Comment by Andiweli** [comment]
Ok, lets try... attached a log file with all log entries from the plugin.

[iobroker.current.log.html.zip](https://github.com/merdok/homebridge-xiaomi-fan/files/6804275/iobroker.current.log.html.zip)

Update: Tried with .p10 now again...
Angles are recognized, also Natural-mode and the 4-levels.
Still always "false" at Buzzer and LED.

When I switch back to .p18 without deleting the data entries they remain "false" again.

**Comment by merdok** [comment]
This is unfortunately not a homebridge debug log... I need a debug log from homebridge.

**Comment by Andiweli** [comment]
Its ioBroker with a Homebridge wrapper.
Thats the only log I have in the GUI.

**Comment by merdok** [comment]
I will unfortunately not able to figure out what the problem is with that log, since that log does not tell me anything...

**Comment by Andiweli** [comment]
I am now using the .p10 for configuration which is working except LED and Buzzer (which I don't need). Everything else seems to work - natural-mode, fan levels, even the angles.

Perhaps you can use the same settings from the .p10 for the .p18 to get it work better.

**Comment by merdok** [comment]
The p18 is already using the exact same settings as the p10 so they should both behave the same... 

Again in order for me to provide any reasonable help I need the homebridge debug log since everything is right now just speculations.
