### ISSUE TITLE
Xiaomi Fan 2S Not connecting with the new update

### ISSUE THREAD

**Issue by recovery86** [merdok/homebridge-xiaomi-fan#102]
Hello 

I need your help I have a Problem with my fan 

Since the new update 1.5.4 and 1.5.5 my fan no longer connects automatically with the plugin. I already tried to delete the fan and reinserted it. That didn't work. with plugin 1.5.3, everything worked fine.

**Comment by merdok** [comment]
Nothing changed with version 1.5.4 or 1.5.5 which might have affected your fan. Besides that i also have a xiaomi fan 2s and it works fine with the latest version. I would guess that your token might have changed for some reason...
You can also post a homebridge debug log so i can check what the issue on your side might be.

**Comment by recovery86** [comment]
ok thanks already

the token is unfortunately not the reason.
It connects when I restart the homebridge then it works until it is disconnected from the power or when I turn it off, it loses the connection after half an hour when I switch it on again, it no longer connects. when I install version 1.5.3 it works

I can't do debug mode unfortunately.

Thanks

**Comment by merdok** [comment]
Without a proper homebridge debug log i will unfortunately not be able to help you. If it is like you described it, then i need to see the log to have at least a slightest idea what is happening in your environment.
