### ISSUE TITLE
Swing mode switch for `dmaker.fan.1c`?

### ISSUE THREAD

**Issue by afharo** [merdok/homebridge-xiaomi-fan#103]
Hi! Thanks for this plugin!

I was wondering if we could have a switch to enable/disable the swing mode. Maybe reuse the _rotation_ button of the fan to this purpose? Thank you!

```
[20/07/2021, 13:09:46] [xiaomifan] [Fresquito] Got initial fan properties:
 {
   "power": true,
   "fan_level": 2,
   "child_lock": false,
   "swing_mode": true,
   "power_off_time": 0,
   "buzzer": false,
   "light": true,
   "mode": 0
}
```

**Comment by afharo** [comment]
oh! Nevermind! I noticed the _Oscillate_ option. Oddly enough... when the tiles are merged, it is not shown 😕

**Comment by merdok** [comment]
Yes, it is hidden on the fan accessory, not on the group. This is the default way to enable/disable swing mode in HomeKit. If you want to have a dedicated switch to enable/disable the swing mode then you can use my other plugin https://github.com/merdok/homebridge-miot where you can enable such switch for direct access. It also has some other features like steeples fan speed emulation.
