### ISSUE TITLE
Please add support for airmate fan namely air.fan.ca23ad9

### ISSUE THREAD

**Issue by huongminh** [merdok/homebridge-xiaomi-fan#105]
Hi merdok,
I've been using your plugin and found it great with my smartmi fans. But unfortunately the plug in does not work with my new air mate fan of air.fan.ca23ad9. Please add support for it. 

this is what I got from lthe link
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:air-ca23ad9:1

{"type":"urn:miot-spec-v2:device:fan:0000A005:air-ca23ad9:1","description":"Fan","services":[{"iid":1,"type":"urn:miot-spec-v2:service:device-information:00007801:air-ca23ad9:1","description":"Device Information","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:manufacturer:00000001:air-ca23ad9:1","description":"Device Manufacturer","format":"string","access":["read"]},{"iid":2,"type":"urn:miot-spec-v2:property:model:00000002:air-ca23ad9:1","description":"Device Model","format":"string","access":["read"]},{"iid":3,"type":"urn:miot-spec-v2:property:serial-number:00000003:air-ca23ad9:1","description":"Device Serial Number","format":"string","access":["read"]},{"iid":4,"type":"urn:miot-spec-v2:property:firmware-revision:00000005:air-ca23ad9:1","description":"Current Firmware Version","format":"string","access":["read"]}]},{"iid":2,"type":"urn:miot-spec-v2:service:fan:00007808:air-ca23ad9:1","description":"Fan","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:air-ca23ad9:1","description":"Switch Status","format":"bool","access":["write","notify"]},{"iid":2,"type":"urn:miot-spec-v2:property:fan-level:00000016:air-ca23ad9:1","description":"Fan Level","format":"uint8","access":["write","notify"],"value-range":[1,32,1]},{"iid":3,"type":"urn:miot-spec-v2:property:horizontal-swing:00000017:air-ca23ad9:1","description":"Horizontal Swing","format":"bool","access":["write","notify"]},{"iid":4,"type":"urn:miot-spec-v2:property:vertical-swing:00000018:air-ca23ad9:1","description":"Vertical Swing","format":"bool","access":["write","notify"]},{"iid":5,"type":"urn:miot-spec-v2:property:mode:00000008:air-ca23ad9:1","description":"Mode","format":"uint8","access":["write","notify"],"value-list":[{"value":1,"description":"Basic"},{"value":2,"description":"Baby Care"}]}]}]}

**Comment by merdok** [comment]
Support has been added in version 1.5.7. Please try it out and let me know!
