### ISSUE TITLE
Customizable sub-service names?

### ISSUE THREAD

**Issue by SR2k** [merdok/homebridge-xiaomi-fan#106]
This plugin uses hard-coded names for sub-services (like Natural mode, LED and buzzer). And when displayed as a single device, you cannot edit names of such services using Home app.

This might be OK for English speakers, but for my cases, you have to talk to Siri with two different languages, e.g.: `(Chinese here, means hey Siri turn on) /hey siri da kai/ (suddenly English) buzzer`.

And unfortunately, when configured to speak Chinese, the one and only Siri just won't understand your mixed language.

If add support for users to config names for the sub-services like the FanV2 service, this problem might be solved.

**Comment by merdok** [comment]
Hi,

sorry I am not quite sure what you mean...
You can rename any of the services created with the plugin, this is a native HomeKit functionality. Just enter the list of services in the group, open the details page for a service and rename the service there.
Is this what you are looking for?

**Comment by SR2k** [comment]
Ah, thank u for your time :)

I've got that you have to split the services into single ones and edit the names, then join them again.
