### ISSUE TITLE
Mi Smart Standing Fan 3 can not be imported anymore

### ISSUE THREAD

**Issue by Besmaen** [merdok/homebridge-xiaomi-fan#108]
Hello and thank you for the great plug in,

It worked for weeks but unfortunatly the plugin is not working for the Smartmi Standing Fan 3 anymore.

I reinstalled the plug in but it did not help.

Could you please help with this error?

Best regards
Sebastian

**Comment by merdok** [comment]
Hi,

I suppose that your token did change, that could be the only explanation. You can also provide some homebridge debug log so I can check if there is anything that indicated about the problem.
