### ISSUE TITLE
Battery mode

### ISSUE THREAD

**Issue by edelmaca** [merdok/homebridge-xiaomi-fan#11]
Hey,
Is it somehow possible to get the info if the fan is running on battery or from mains?

I have some automations going that are suitable just for the fixed position on main. But if I unplug it and set it up somewhere else, let it run on battery, these automations shouldn’t run and therefore it would be nice to let the automations and triggers know if it is running on battery or not.
Maybe there is some data hidden underneath. 🤷🏻‍♂️

**Comment by merdok** [comment]
Hi,
as far as I know you cannot get this information from any of the latest xiaomi fans anymore. I know that on some older fans it was possible to at least read out the battery level but xiaomi removed that in their latest models. So I guess that this will most likely be not possible...

**Comment by edelmaca** [comment]
Oh man, that sucks. So i have to get around this problem with some other tricks and ideas.

Thanks for your answer.
