### ISSUE TITLE
Percentage controller doesn't work for zhimi.fan.za5 (Smartmi Standing Fan 3)

### ISSUE THREAD

**Issue by pwiepengel** [merdok/homebridge-xiaomi-fan#111]
The percentage controller doesn't work, all other controller (switches) are working fine

**Comment by merdok** [comment]
With the little info you provided it is impossible to tell what the issue on your side is...
Anyway, you can try out the https://github.com/merdok/homebridge-miot plugin which has at this point better support for fans.
