### ISSUE TITLE
If Fan is restarted, no response until homebridge restart

### ISSUE THREAD

**Issue by clldr** [merdok/homebridge-xiaomi-fan#112]
Hey there,

When my fan either drops Wifi then reconnects or is unplugged then plugged back in, the plugin can no longer communicate with the fan until homebridge is restarted. 

Logs in debug mode show communication errors but I am able to ping the fan from the homebridge host. A simple restart of homebridge reconnects the device. Is this an issue you are aware of?

The fan is a Standing Fan X1 (dmaker.fan.p5)

[5/23/2022, 5:46:19 PM] [xiaomifan] [Hall Fan] Error: Network communication is unavailable, device might be destroyed
[5/23/2022, 5:46:19 PM] [xiaomifan] [Hall Fan] Could not connect to the fan! Retrying in 60 seconds!

**Comment by merdok** [comment]
That is strange and should not happen. I will have a look, but i would anyway recommend to use the homebridge-miot plugin if possible as that one is more advanced.

**Comment by merdok** [comment]
I had a look and could not find anything that might causing this. I have added an extra log there just in case when it happens again, if it does please post the new log here.

**Comment by clldr** [comment]
Thanks, I rolled back to 1.5.4 and the issue appears to have gone so I’ll just use that version.



- Hayden 



Here's to the crazy ones

**Comment by 2000one** [comment]
> Hey there,
> 
> When my fan either drops Wifi then reconnects or is unplugged then plugged back in, the plugin can no longer communicate with the fan until homebridge is restarted.
> 
> Logs in debug mode show communication errors but I am able to ping the fan from the homebridge host. A simple restart of homebridge reconnects the device. Is this an issue you are aware of?
> 
> The fan is a Standing Fan X1 (dmaker.fan.p5)
> 
> [5/23/2022, 5:46:19 PM] [xiaomifan] [Hall Fan] Error: Network communication is unavailable, device might be destroyed [5/23/2022, 5:46:19 PM] [xiaomifan] [Hall Fan] Could not connect to the fan! Retrying in 60 seconds!

Same issue for me with zhimi.fan.za4 but no errors found in log…

**Comment by clldr** [comment]
Thanks, the miot plug-in doesn’t work as it sets the fan to 4% when the HomeKit fan is set to 100%. Yours is better as it works properly! Aside from the none response issue 



- Hayden 



Here's to the crazy ones
