### ISSUE TITLE
Add dmaker.fan.p30 support

### ISSUE THREAD

**Issue by larryemi** [merdok/homebridge-xiaomi-fan#114]
Found this fan with humidity and temperature sensor. Can you please add this fan to support?

Device Name: Xiaomi Smart Standing Fan 2 Pro
Device Model: dmaker.fan.p30
Model Number: 
Mito Spec: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p30:1

Thank you.

**Comment by merdok** [comment]
Added in 1.5.8
