### ISSUE TITLE
Could you please add new device?

### ISSUE THREAD

**Issue by jajugoguma** [merdok/homebridge-xiaomi-fan#115]
Thanks for making a great plug-in!

I have a Xiaomi fan but it does not seem to be supported.

Device Model: dmaker.fan.p220
miot spec: https://home.miot-spec.com/spec/dmaker.fan.p220

Could you please add a new device?

**Comment by merdok** [comment]
I could add that, but can you tell me what is the name (marketing name) of the device? It seems that is only available in china so i am not sure how to name it...

**Comment by jajugoguma** [comment]
I also purchased the product translated into Korean, so I can't know the exact marketing name. However, based on the name written in Chinese and Korean, it appears to be the [Mijia DC Inverter Circulating Floor Fan Battery Version](https://xiaomipedia.com/en/p/mijia-dc-inverter-circulating-floor-fan-battery-version/), to my guess.

**Comment by merdok** [comment]
The fan should now be supported as of version 1.5.9! 
Btw, you can also checkout my other plugin https://github.com/merdok/homebridge-miot which in general has better fan support, especially if you are using newer fans like the p220.
