### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by Vicelow** [merdok/homebridge-xiaomi-fan#117]
Hi there, any idea how to set a static IP for the fan? It keeps changing via DHCP and so the plug-in stops working… I can’t find an option to make it static in the Xiaomi app. Or is there another solution? Many thanks

**Comment by merdok** [comment]
You have to give a static IP to your fan in your router based on the fan mac adress.

**Comment by Vicelow** [comment]
That was it. brilliant - thank you! So much more useful now…
