### ISSUE TITLE
Feature request: Reverse natural mode

### ISSUE THREAD

**Issue by Stichoza** [merdok/homebridge-xiaomi-fan#118]
It would be great if there was an ability to reverse the Natural Mode switch. It's turned on most of the time anyways, so it will make Home app cleaner for me to reverse the switch and call it Standard Mode instead. So natural mode will be turned on when you turn off that switch.

Main reason behind it is that you might say "Hey Siri, turn off all switches" to turn off other smart switches in home but natural mode is also turned off along with smart switches and stuff.

**Comment by merdok** [comment]
Hi, 
what switch is being shown is dependent on the actual fan model used. Some fans only support natural mode but others also support sleep mode, including logic for reverse would require some adjustments.
Not sure what fan you are using, but you can try my other plugin homebridge-miot which has in general better fan support (successor of this plugin) and also allows you to completely customize your accessory with some config adjustments. It might be possible to accomplish what you desire there.
