### ISSUE TITLE
Fans keep connecting and disconnecting every few seconds

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-xiaomi-fan#12]
As the title says my two 2s keep connecting and disconnecting every few seconds.

This is what the plugin reports in console:

```
Jun 24 13:43:17 homebridge[388]: [6/24/2020, 1:43:17 PM] [Ventilator Schlafzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:43:35 homebridge[388]: [6/24/2020, 1:43:35 PM] [Ventilator Schlafzimmer] Xiaomi Fan - found Fan in network. Trying to connect...
Jun 24 13:43:35 homebridge[388]: [6/24/2020, 1:43:35 PM] [Ventilator Schlafzimmer] Xiaomi Fan - connected to Fan
Jun 24 13:43:35 homebridge[388]: [6/24/2020, 1:43:35 PM] [Ventilator Schlafzimmer] MiioDevice {
Jun 24 13:43:35 homebridge[388]:   model=zhimi.fan.za4,
Jun 24 13:43:35 homebridge[388]:   types=miio,
Jun 24 13:43:35 homebridge[388]:   capabilities=
Jun 24 13:43:35 homebridge[388]: }
Jun 24 13:43:38 homebridge[388]: 100
Jun 24 13:43:47 homebridge[388]: [6/24/2020, 1:43:47 PM] [Ventilator Wohnzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:43:47 homebridge[388]: [6/24/2020, 1:43:47 PM] [Ventilator Schlafzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:43:56 homebridge[388]: [6/24/2020, 1:43:56 PM] [Ventilator Schlafzimmer] Xiaomi Fan - found Fan in network. Trying to connect...
Jun 24 13:43:56 homebridge[388]: [6/24/2020, 1:43:56 PM] [Ventilator Schlafzimmer] Xiaomi Fan - connected to Fan
Jun 24 13:43:56 homebridge[388]: [6/24/2020, 1:43:56 PM] [Ventilator Schlafzimmer] MiioDevice {
Jun 24 13:43:56 homebridge[388]:   model=zhimi.fan.za4,
Jun 24 13:43:56 homebridge[388]:   types=miio,
Jun 24 13:43:56 homebridge[388]:   capabilities=
Jun 24 13:43:56 homebridge[388]: }
Jun 24 13:44:05 homebridge[388]: [6/24/2020, 1:44:05 PM] [Ventilator Wohnzimmer] Xiaomi Fan - found Fan in network. Trying to connect...
Jun 24 13:44:05 homebridge[388]: [6/24/2020, 1:44:05 PM] [Ventilator Wohnzimmer] Xiaomi Fan - connected to Fan
Jun 24 13:44:05 homebridge[388]: [6/24/2020, 1:44:05 PM] [Ventilator Wohnzimmer] MiioDevice {
Jun 24 13:44:05 homebridge[388]:   model=zhimi.fan.za4,
Jun 24 13:44:05 homebridge[388]:   types=miio,
Jun 24 13:44:05 homebridge[388]:   capabilities=
Jun 24 13:44:05 homebridge[388]: }
Jun 24 13:44:27 homebridge[388]: [6/24/2020, 1:44:27 PM] [Ventilator Wohnzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:44:27 homebridge[388]: [6/24/2020, 1:44:27 PM] [Ventilator Schlafzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Wohnzimmer] Xiaomi Fan - found Fan in network. Trying to connect...
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Wohnzimmer] Xiaomi Fan - connected to Fan
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Wohnzimmer] MiioDevice {
Jun 24 13:44:36 homebridge[388]:   model=zhimi.fan.za4,
Jun 24 13:44:36 homebridge[388]:   types=miio,
Jun 24 13:44:36 homebridge[388]:   capabilities=
Jun 24 13:44:36 homebridge[388]: }
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Schlafzimmer] Xiaomi Fan - found Fan in network. Trying to connect...
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Schlafzimmer] Xiaomi Fan - connected to Fan
Jun 24 13:44:36 homebridge[388]: [6/24/2020, 1:44:36 PM] [Ventilator Schlafzimmer] MiioDevice {
Jun 24 13:44:36 homebridge[388]:   model=zhimi.fan.za4,
Jun 24 13:44:36 homebridge[388]:   types=miio,
Jun 24 13:44:36 homebridge[388]:   capabilities=
Jun 24 13:44:36 homebridge[388]: }
Jun 24 13:45:07 homebridge[388]: [6/24/2020, 1:45:07 PM] [Ventilator Schlafzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
Jun 24 13:45:47 homebridge[388]: [6/24/2020, 1:45:47 PM] [Ventilator Wohnzimmer] Xiaomi Fan - lost connection to fan. Disconnecting...
```

**Comment by merdok** [comment]
Does it also happen when you just have 1 fan in your config?

**Comment by CooperCGN** [comment]
I removed one and it still happens. Whenever it says "disconnecting..." the fan turns off in the Home app and turns back on when it has reconnected.

**Comment by merdok** [comment]
What is your pollingInterval config value? You could try to set it higher.

**Comment by h0mesmart** [comment]
I do have exactly the same issue even with the latest version. I have 10s as polling interval.

**Comment by merdok** [comment]
Can you try to do a ping on your fan for like 60 seconds and check if all the requests go to the fan?

**Comment by h0mesmart** [comment]
here are the ping result, fyi I do have 2 fans both 2s model. 
first fan ping result : 60 packets transmitted, 54 packets received, 10.0% packet loss
round-trip min/avg/max/stddev = 24.260/288.200/770.221/236.937 ms
2nd fan ping result : 60 packets transmitted, 60 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 23.113/248.965/909.198/229.435 ms

**Comment by merdok** [comment]
So you have 10% packet loss on one of your fans this of course can lead that the fan disconnects. Can Kyu repeat the ping test a few more times and see if that is consistent?

**Comment by h0mesmart** [comment]
1st with packet loss : Reset its wifi. Redo some ping test on both, several times. Here are the result 
--- 10.0.0.131 ping statistics ---
31 packets transmitted, 31 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 41.374/254.482/675.112/195.440 ms
--- 10.0.0.135 ping statistics ---
30 packets transmitted, 30 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.374/195.860/776.659/201.672 ms
--- 10.0.0.135 ping statistics ---
30 packets transmitted, 28 packets received, 6.7% packet loss
round-trip min/avg/max/stddev = 24.206/243.676/636.239/216.048 ms
--- 10.0.0.131 ping statistics ---
30 packets transmitted, 29 packets received, 3.3% packet loss
round-trip min/avg/max/stddev = 34.463/183.584/645.092/156.925 ms
--- 10.0.0.135 ping statistics ---
30 packets transmitted, 27 packets received, 10.0% packet loss
round-trip min/avg/max/stddev = 30.863/197.703/642.409/191.339 ms
--- 10.0.0.135 ping statistics ---
30 packets transmitted, 30 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 27.865/296.865/838.193/252.227 ms
--- 10.0.0.131 ping statistics ---
30 packets transmitted, 30 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 18.538/270.746/735.093/249.462 ms

and here are the homebridge logs 

29/06/2020, 20:56:10 [Ventilateur] Xiaomi Fan - lost connection to fan. Disconnecting...
29/06/2020, 20:56:19 [Ventilateur] Xiaomi Fan - found Fan in network. Trying to connect...
29/06/2020, 20:56:19 [Ventilateur] Xiaomi Fan - connected to Fan
29/06/2020, 20:56:19 [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}
29/06/2020, 20:56:50 [Ventilateur] Xiaomi Fan - lost connection to fan. Disconnecting...
29/06/2020, 20:56:59 [Ventilateur] Xiaomi Fan - found Fan in network. Trying to connect...
29/06/2020, 20:56:59 [Ventilateur] Xiaomi Fan - connected to Fan
29/06/2020, 20:56:59 [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}
29/06/2020, 20:57:20 [Ventilateur] Xiaomi Fan - lost connection to fan. Disconnecting...
29/06/2020, 20:57:29 [Ventilateur] Xiaomi Fan - found Fan in network. Trying to connect...
29/06/2020, 20:57:29 [Ventilateur] Xiaomi Fan - connected to Fan
29/06/2020, 20:57:29 [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}
29/06/2020, 20:58:30 [Ventilateur] Xiaomi Fan - lost connection to fan. Disconnecting...
29/06/2020, 20:58:39 [Ventilateur] Xiaomi Fan - found Fan in network. Trying to connect...
29/06/2020, 20:58:39 [Ventilateur] Xiaomi Fan - connected to Fan
29/06/2020, 20:58:39 [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}

**Comment by merdok** [comment]
Basically it disconnects because the ping fails. I check the fan status be pinging the device so if a ping fails then it disconnects. Your fan somehow loosing pretty often pings. You could try to set a higher polling interval.

**Comment by h0mesmart** [comment]
I set a 30s polling interval. The log do not mention any disconnecting , so far so good. I’ll update this issue if something change. Thank you for your help

**Comment by h0mesmart** [comment]
Update : 
6/29/2020, 9:58:39 PM [Ventilateur] Xiaomi Fan - connected to Fan
6/29/2020, 10:12:40 PM [Ventilateur] Xiaomi Fan - lost connection to fan. Disconnecting...
6/29/2020, 10:13:09 PM [Ventilateur] Xiaomi Fan - found Fan in network. Trying to connect...
6/29/2020, 10:13:09 PM [Ventilateur] Xiaomi Fan - connected to Fan

**Comment by merdok** [comment]
I think your network is unstable (at least the connection to the fan). You need to make sure that no ping packets are lost. This is very important, since i need to ping the fan to see if it is available or not. It can also be that your router is blocking some of the pings somehow. 
Setting the polling interval even higher will for sure make less disconnects.

Just to make sure, i tested it with my fan and even after around 10 minutes of continuous ping not a single packet got lost on my setup...

**Comment by CooperCGN** [comment]
Not sure if it is really network related or the fans. I did a ping on both of them 60 times and then a ping on a Dyson air humidifier I have installed. These are the results, all show no package loss but the fans have a lot higher ping times.

--- 10.0.1.238 ping statistics ---
60 packets transmitted, 60 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 26.838/237.893/800.106/205.901 ms

--- 10.0.1.239 ping statistics ---
60 packets transmitted, 60 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 18.129/265.745/695.963/193.381 ms

--- 10.0.1.78 ping statistics ---
60 packets transmitted, 60 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.127/14.493/142.534/30.902 ms

**Comment by h0mesmart** [comment]
I’m at work so cannot test. I’ll do some test later this evening, I have a mi bedside lamp not to far away from one fan, I’ll run a ping on both device to see what’s up. Will keep you updated

**Comment by merdok** [comment]
@CooperCGN the point is that the connection to the fan needs to be stable, whether it is a network, router or some other issue. The plugin does nothing else then periodically ping the fan in order to check if the fan is still reachable, and when the ping results in an error then the fan disconnects since I assume that it is not available anymore.

@h0mesmart ok👍🏻

Since this is a local issues on your side and I cannot reproduce that, you need to investigate this and let me know what caused the issue, and if it is related to the plugin then I will do the adjustments.

**Comment by merdok** [comment]
Since version 1.0.0 i do not depend on the ping anymore to detect the fan status. This should be more reliable. Could you check now?

**Comment by h0mesmart** [comment]
V1.0.0 installed at 6:34 PM no trace of disconnected in the log so far. 

7/6/2020, 6:23:32 PM [Vito] [Vito] Found Fan zhimi.fan.za4
7/6/2020, 6:23:32 PM [Vito] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}
7/6/2020, 6:23:32 PM [Ventilateur] [Ventilateur] Found Fan zhimi.fan.za4
7/6/2020, 6:23:32 PM [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}

I did see a another connection at 7:00 PM

 7/6/2020, 7:00:57 PM [Vito] [Vito] Connected to Fan zhimi.fan.za4
7/6/2020, 7:00:57 PM [Vito] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}
7/6/2020, 7:00:57 PM [Ventilateur] [Ventilateur] Connected to Fan zhimi.fan.za4
7/6/2020, 7:00:57 PM [Ventilateur] MiioDevice {
  model=zhimi.fan.za4,
  types=miio,
  capabilities=
}

Polling is set at 60s

**Comment by merdok** [comment]
So i understand it is better now?

**Comment by CooperCGN** [comment]
Installed it an hour ago and the problem seems to be resolved. Great work! I will check every few hours if something “strange” happens. Btw I left the polling at 10 seconds.

**Comment by h0mesmart** [comment]
> So i understand it is better now?

👍 thank you so much

**Comment by merdok** [comment]
Sounds good! So I guess this can be closed!
