### ISSUE TITLE
Smartmi Fan 3 not working

### ISSUE THREAD

**Issue by louis-sicko** [merdok/homebridge-xiaomi-fan#121]
Hi,

i pulled the token and setup the plugin in homebridge. It showed up but the controls didnt work and the device timed out. After that i lost even control over the Xiaomi App and the remote.

**Comment by merdok** [comment]
You need to post some homebridge debug log so that I can have a look what might be wrong.

**Comment by louis-sicko** [comment]
Hi i retried it for the 5th time and now it works. Thanks!
