### ISSUE TITLE
iOS 16 Beta 8 - fan doesn't show left right and natural mode

### ISSUE THREAD

**Issue by 4rianton** [merdok/homebridge-xiaomi-fan#123]
![image](https://user-images.githubusercontent.com/7961281/188504288-73e53832-48f7-492b-a9fc-7522626691c0.png)

Just wanted to post here about how the left/rich/natural mode buttons are all labeled by the same name in iOS 16 Beta 8.

**Comment by merdok** [comment]
This is already a known issue. Something unfortunately changed in Homekit in iOS16 which is causing that. It is neither an issue with this plugin or with homebridge and there is nothing currently that can be done against it. We will have to wait and see if that will change in the future.

**Comment by roboterm** [comment]
There is a solution:

- Edit the name of the switch
- erase all letters
- the former name is displayed as suggestion so you can change it to the name it formally had

**Comment by jain-blueid** [comment]
> There is a solution:
> 
> * Edit the name of the switch
> * erase all letters
> * the former name is displayed as suggestion so you can change it to the name it formally had

this works for me, thanks @roboterm

**Comment by redschumi** [comment]
@roboterm 

Thanks for the solution. Works
Addition: Edit has to be done in Home-App on iOS, not in Homebridge

**Comment by maisun** [comment]
Thanks for the solution!
