### ISSUE TITLE
iOS 16: all switches in the group have the same name

### ISSUE THREAD

**Issue by maisun** [merdok/homebridge-xiaomi-fan#124]
Hi, after upgrading to iOS 16 in the device group looks like all switches now inherit the name of the main accessory. Is it an issue with iOS or homebridge? Many thanks!

**Comment by redschumi** [comment]
Have same issue. Delete devices in homebridge an make it new doesn’t fix it.

**Comment by roboterm** [comment]
Already solved.  

https://github.com/merdok/homebridge-xiaomi-fan/issues/123

**Comment by merdok** [comment]
Not a bug with the plugin, but has something to do with a change in iOS16. As far as i know there is nothing at this point that i can do...
Please see https://github.com/homebridge/homebridge/issues/3210#issuecomment-1217735865
