### ISSUE TITLE
no connection after a while

### ISSUE THREAD

**Issue by sadden3194** [merdok/homebridge-xiaomi-fan#126]
Hi!

I have used the fan and then turned it off. If I do not use it for a few hours and then want to switch it on again via homebrdige or Xiaomi Home app, it is displayed as offline. Only when I switch on the fan manually on the device, I can operate it again via the app a few seconds later.

Model: Smartmi Pedestal Fan 3

**Comment by merdok** [comment]
This is not an issue with the plugin. The fan goes into a sleep mode to preserve battery life (this includes turning off the wifi module) when not plugged into the outlet. There is nothing that can be done, expect leaving it plugged into an outlet.

**Comment by sadden3194** [comment]
I see. But is there no way to prevent the sleep mode with your plugin?
For example a permanent ping to the device or anything else to keep the device awake?

**Comment by merdok** [comment]
The only way is to plug your fan into an outlet.

**Comment by sadden3194** [comment]
Okay thank you very much! :)

**Comment by wapster182** [comment]
Hello @merdok, I have a similar issue with my fan, model Standing Fan 2s. It IS always plugged into an outlet, and also can be activated after a few hours/days with the official Mi Home App.
But within HomeKit, this does not work after it went so sleep/standby. Shouldn't plugging it into an outlet prevent it from going offline? It seems it does but only for the Mi Home App, not via HomeKit control.

**Comment by merdok** [comment]
It should make no difference when its plugged into an outlet whether you try to turn it on using the mi home app or homekit. As long as the device i reachable in your network, both should work...
