### ISSUE TITLE
new device support

### ISSUE THREAD

**Issue by pb29** [merdok/homebridge-xiaomi-fan#127]
hello, is it able to support another device that doesn't on the list?
it's a wired circulator fan. and model code is dmaker.fan.p28, I think it's china only domestic model but I overseas purchase to use it.
here's the product page https://www.xiaomiyoupin.com/detail?gid=154295
I was able to adding it to homekit and some features are works but they're all mismatched name buttons and so.
here's the full screenshot of mi home app remote screen
`

> ![IMG_7179](https://user-images.githubusercontent.com/26969207/193448394-929ff44c-5d5a-49b4-aa33-f123354f9e5d.jpeg)

`

**Comment by merdok** [comment]
Please have a look at https://github.com/merdok/homebridge-miot
It might be supported there.

**Comment by pb29** [comment]
oooh, nice. I have to move on to that one then. thanks!
