### ISSUE TITLE
Any chance this should work with Viomi Standing floor fan?

### ISSUE THREAD

**Issue by gjlamb** [merdok/homebridge-xiaomi-fan#128]
I installed the plugin on Hoobs and configured the ip and token in advance configuration as per the sample.  My Hoobs log has the following reporting no devices.

4/10/2022, 1:30:23 pmXiaomi Fan Bridge starting
4/10/2022, 1:30:42 pmXiaomi Fan BridgeLoaded plugin 'homebridge-xiaomi-fan'
4/10/2022, 1:30:42 pmXiaomi Fan BridgeLoading 1 platforms...
4/10/2022, 1:30:42 pmXiaomi Fan BridgexiaomifanInit - initializing devices
4/10/2022, 1:30:42 pmXiaomi Fan Bridgexiaomifan-------------------------------------------
4/10/2022, 1:30:42 pmXiaomi Fan BridgexiaomifanInit - no fan configuration found
4/10/2022, 1:30:42 pmXiaomi Fan BridgexiaomifanMissing devices or fans in your platform config
4/10/2022, 1:30:42 pmXiaomi Fan Bridgexiaomifan-------------------------------------------
4/10/2022, 1:30:42 pmXiaomi Fan BridgeBridge is running on port 51876.
4/

**Comment by merdok** [comment]
As the log states, you are missing a config for the plugin or you have an error in your config

**Comment by gjlamb** [comment]
Thanks.  Went through the Bridge form (+ add device) instead of copy/pasting the example into Advanced.  Fan now shows up in Apple Home.

However, there's 8 Poweron toggles in the device in Apple Home.  Status doesn't stay on screen after sliding first button up to xx%
![Screenshot 2022-10-05 at 11 04 49 am](https://user-images.githubusercontent.com/50600785/193952379-d4f31c76-526d-49aa-8b8c-abe741108ee5.png)

**Comment by merdok** [comment]
This is a known ios16 issue, the only way for you to fix that is to  manually rename all the switches to the desired name.
