### ISSUE TITLE
Cannot connect to smart standing fan 2

### ISSUE THREAD

**Issue by ghost** [merdok/homebridge-xiaomi-fan#129]
Hi,

I seem to be having an issue with the plugin not connecting to a xiaomi smart standing fan 2 (dmaker.fan.p18). The error says this:

![Screenshot 2023-01-23 124132](https://user-images.githubusercontent.com/78227107/214031778-562386d7-f725-439e-9b21-1651f0f3af66.png)

I am running HB on a Raspberry Pi 4 with HB v1.6.0 and Node v18.13.0. The Plugin is running on v1.5.9.

I have already checked that all the needed data is correct (Token, ID, Name, etc.) and have tried using previous versions of the plugin.
Thanks in advance!

**Comment by merdok** [comment]
Hi,
the handshake timeout is usually caused by an invalid token. Are you sure that the token is correct?

**Comment by ghost** [comment]
Thanks for the fast reply!

So I used the Token-extractor from https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor and copied the token directly from the terminal, so maybe the token extractor isn't reliable? Would you know of another way to find out my device token so I could maybe compare?

**Comment by merdok** [comment]
The token extractor gets the token from the cloud, which might be not up to date. If you reset your device but did not connect to the cloud then an outdated token might be stored there. You would need to reset your device and add it to the xiaomi home app and make sure that you are signed in with your account.

**Comment by ghost** [comment]
So I tried resetting the fan, then reconnected it to the xiaomi home app and when I used the token extractor I got a new token. Using the new token however, is still giving me the same timeout error.

**Comment by merdok** [comment]
That is odd, did you try the homebridge-miot plugin for your fan?

**Comment by ghost** [comment]
I have tried it now, and am still getting the same handshake timeout error; I am beginning to suspect, that it might be an issue in my internal network

**Comment by merdok** [comment]
If you get the same error then your issue is either indeed a network issue or still might be an incorrect token.

**Comment by reboot81** [comment]
Had the same issue, solved it by restarting Wifi.
