### ISSUE TITLE
Fan connected but error requesting dmaker fan properties

### ISSUE THREAD

**Issue by quahctb** [merdok/homebridge-xiaomi-fan#13]
The fan seems to connect successfully but there seems to be an error while requesting fan properties.

This is the homebridge log:
```
[6/25/2020, 2:39:13 PM] [My Xiaomi Fan] Initializing xiaomifan accessory...
[6/25/2020, 2:39:33 PM] [My Xiaomi Fan] Xiaomi Fan - found Fan in network. Trying to connect...
[6/25/2020, 2:39:33 PM] [My Xiaomi Fan] Xiaomi Fan - connected to Fan
[6/25/2020, 2:39:33 PM] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.1c,
  types=miio,
  capabilities=
}
[6/25/2020, 2:39:33 PM] [My Xiaomi Fan] Xiaomi Fan - fan model info file already exists, not saving!
[6/25/2020, 2:39:45 PM] [My Xiaomi Fan] Xiaomi Fan - error while requesting dmaker fan properties: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
```

My fan config:

```
{
            "name": "My Xiaomi Fan",
            "ip": "192.168.1.212",
            "token": "fe2b5e2833a98418ec59c609e21700b7",
            "prefsDir": "/homebridge/.xiaomiFan",
            "pollingInterval": 20,
            "moveControl": false,
            "buzzerControl": false,
            "ledControl": false,
            "accessory": "xiaomifan"
}
```

**Comment by merdok** [comment]
Well, the problem is that xiaomi has a lot of mess and each fan has its own remote api, without physical access to every different model it will be hard to get all fans to work...

**Comment by merdok** [comment]
If you want me to add support for your fan then you would need to dump the commands from your fan. Would you willing to do that?

**Comment by quahctb** [comment]
Yes, I will be glad to do that. But how do I go about it?

**Comment by merdok** [comment]
It requires a a couple of steps to be done. You can basically read here how to dump commands from your device:
https://github.com/aholstenson/miio/blob/master/docs/protocol.md
https://github.com/jghaanstra/com.robot.xiaomi-mi

**Comment by quahctb** [comment]
I been trying to retrieve the command via Wireshark. But it seems that with the latest version of the mihome app, turning the fan on/off doesn't generate a UDP. The only time a UDP was sent was only when I enter the fan details and the UDP sent was to get the fan properties. Other than that, no UDP was being sent. 

I tried both on BlueStacks via ethernet and wifi and also via the iPhone cable connected to the Mac with Wireshark.

Not too sure what is the issue or is there anything that I missed?

**Comment by merdok** [comment]
Maybe something changed in the newer fans. Do you at least have the fan properties?

**Comment by terriblefox** [comment]
[7/16/2020, 6:48:51 PM] Loading 1 accessories...
[7/16/2020, 6:48:51 PM] [My Xiaomi Fan] Initializing xiaomifan accessory...
[7/16/2020, 6:48:51 PM] [My Xiaomi Fan] Xiaomi Fan - fan model info file does not exist

is what I get.


"name": "My Xiaomi Fan",
            "ip": "192.168.0.46",
            "token": "140f0f1011b5223d7958xxxx",
            "pollingInterval": 10,
            "moveControl": false,
            "buzzerControl": false,
            "ledControl": false,
            "naturalModeButton": false,
            "shutdownTimer": false,
            "accessory": "xiaomifan"

**Comment by merdok** [comment]
Like already discussed, someone needs to first extract the commands from the fan, after that i can add support for it.

**Comment by terriblefox** [comment]
Ok , ill try the steps...

**Comment by merdok** [comment]
@terriblefox or @quahctb
I might have discovered something to add support for that, but i need to do some testing with this device. Can you join discord or DM on twitter?

**Comment by terriblefox** [comment]
> @terriblefox or @quahctb
> I might have discovered something to add support for that, but i need to do some testing with this device. Can you join discord or DM on twitter?

im on Discord. StellarPiranha#0595

**Comment by merdok** [comment]
@terriblefox can you join the https://discord.gg/DvWjdU discord, there is a xiaomi-fan channel

**Comment by merdok** [comment]
Initial support for the dmaker.fan.1c is now added in version 1.2.0. Could you check it out?

**Comment by b2un0** [comment]
1c works fine, thanks!

Ca we got a swtich to enable/disable the oscillation mode?

**Comment by merdok** [comment]
There is a switch for that hidden in the device settings in HomeKit

**Comment by b2un0** [comment]
this switch does absolutely nothing with the 1c fan.

**Comment by terriblefox** [comment]
Over here the oscillation  switch works pretty fine ...

**Comment by merdok** [comment]
@b2un0 you could post some debug log so I can check why it is not working for you. Just enable debug log and try to press the switch.
