### ISSUE TITLE
Start/stop swing

### ISSUE THREAD

**Issue by lynx000** [merdok/homebridge-xiaomi-fan#130]
Hello,

Is it possible to start and stop swing with the curved arrow button below the switches?

Is that button being used for anything as default? I haven't managed to figure out what it does :)

![IMG_81543165B44E-1](https://user-images.githubusercontent.com/62328678/234101752-490ac453-2e02-4977-8d37-0f930804a448.jpeg)

**Comment by merdok** [comment]
The button is not really used for the xiaomi devices, it is just being there to make the layout more clean. If that button is removed then the layout gets a little bit messy...

**Comment by lynx000** [comment]
Thank you for the quick reply. I see. It would be cool if it was possible to control the swing. There is a physical button on the device that looks like it. It's referred to in the manual as "Enable/Disable Oscillation".

On the Hunter native Homekit ceiling fans I have seen it used to control the swing direction.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/62328678/234106006-bc246790-3c92-4523-84e0-b4d1946b0a30.png">

**Comment by merdok** [comment]
For oscillation there is already a dedicated button so it does not really make sense to duplicate functionality. On some fans this button can be used to toggle between the buzzer volume level.

**Comment by FMisplon** [comment]
> For oscillation there is already a dedicated button so it does not really make sense to duplicate functionality. On some fans this button can be used to toggle between the buzzer volume level.

I can only find buttons to rotate it a bit to the left or to the right but not to let it start or stop swing all the way from left to right. Am I missing something?
