### ISSUE TITLE
Control Elements don't show their name in the home app

### ISSUE THREAD

**Issue by iliquifysnacks** [merdok/homebridge-xiaomi-fan#131]
![IMG_C5BC4155E672-1](https://user-images.githubusercontent.com/46820607/234939295-7fe53c5c-3a18-49fe-a782-50aca7bda6fa.jpeg)

Thanks a lot for providing this plugin!

I noticed, that in homekit the controll elements work, but are not labled anymore. Is this a known issue?

**Comment by merdok** [comment]
Yeah, well this is an issue with Homekit itself. You can try to rename the switches by yourself and they should stay with the name that you give them.
