### ISSUE TITLE
Support for Homebridge v2.0

### ISSUE THREAD

**Issue by ChrWi** [merdok/homebridge-xiaomi-fan#137]
Hi @merdok 
Homebridge is showing this plugin as „might not be ready for Homebridge v2.0“.
Can you pls check, same as already done for the webos-tv?
thanks a lot!

**Comment by merdok** [comment]
I more or less consider this plugin as legacy... Is there any reason why you have not yet switched to the miot one?

**Comment by ChrWi** [comment]
Let me test this. I only have 2 fans from Xiaomi so never thought to change

**Comment by ChrWi** [comment]
Looks not to bad. I miss the „natural mode control service“ when comparing the settings, but might be a different name. Will check on the weekend

**Comment by merdok** [comment]
It is not w generic plugin so some special stuff per device sometimes is missing, but that can be manually enabled using the `propertyControl` or `actionButtons`

**Comment by ChrWi** [comment]
All good now. „Fetch device data“ is quite useful (having a dmaker.fan.p18). Thanks!

**Comment by merdok** [comment]
Good to hear!
