### ISSUE TITLE
Connection-faillure zhimi.fan.za4

### ISSUE THREAD

**Issue by bittsii** [merdok/homebridge-xiaomi-fan#14]
Hi merdok,
I do fail to integrate my Fan correctly to the homebridge Setup. 

I did get the Token of the Fan 

resetting wifi
Connect pi to Fan wifi 
request Token (discover)

I then copied the given Token, disconnected the pi from fans wifi and re-added the Fan to the mi home app. 
Afterwards added the Fan to homebridge. 

It was set up and integrated even into HomeKit on my device, but afterwards do only Producer errors in homebridge. 

Did I Miss anything? Might the Token have changed when i re-added the Fan to mi home App?

**Comment by merdok** [comment]
Hi,

yes, i think that the token changes every time when you re-add the device in the Mi home app. In that case you need to retrieve the new token for the device.

**Comment by bittsii** [comment]
does this mean I can either add the Fan to homebridge but not the App or the other way round?
I think it would mean to get the Token the way via resetting the Fan and optain the Token would not be possible in this case?

**Comment by merdok** [comment]
You just reset the fan and obtain the token once. Then you can use the token wherever you want. Both homebridge and mi home App will work.

**Comment by 80-am** [comment]
Hi,

The token changes every time you re-add it. You will have to extract the new token using on of the methods described [here](https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md).

**Comment by bittsii** [comment]
@80-am I used Method 3 and than „Configure as a new device“ in the Linked Description. But it does not work for me :(
At least after the last step the Tooken seem to change... as having an iPhone the only way then would be to optain the Token from an unsecured Backup (what I wont be able to create as my harddisk is too small I guess)?

**Comment by merdok** [comment]
You should retrieve the token from your backup. Just setup your fan device in the mi home app once then get the backup an retrieve the token from there. That is what I did over a year ago and since then everything is working great and the token did not change.

**Comment by basvdploeg** [comment]
@bittsii Try using my method:

https://www.reddit.com/r/homebridge/comments/hcl75o/howto_easy_way_to_obtain_xiaomi_device_tokens/

I just got my S2 and got the token in less 30 seconds. Everything works great now, both in the Mi Home app and Homebridge.

**Comment by 80-am** [comment]
@bittsii I would recommend the "Finder/iTunes backup" approach, alternative if you have jailbroken your device you should be able to ssh into it using the Jailbroken iOS steps.

@basvdploeg This approach is great, although a proprietary software with a high fee for a one time thing seems unnecessary. I've heard there is some people getting their tokens from similar but "free" apps such Fing, although I have not yet tried it.

**Comment by basvdploeg** [comment]
@80-am I'm using it for a lot of other purposes. That's actually how I found this particular solution. 

I believe there are some free alternatives in the Reddit comments, but I haven't tried those.
