### ISSUE TITLE
Angle button power off

### ISSUE THREAD

**Issue by dreamdatcrap** [merdok/homebridge-xiaomi-fan#15]
If I crate an angle button, the fan will start to turn (100°) but I can‘t deactivate that it will stop the movement.

Any ideas? Version is 1.0.0

**Comment by merdok** [comment]
Hi,

if understand correctly, if you want to stop the oscillation then you need to disable it on the fan accessory. The buttons should only be a help to set a custom angle, and to disable you need to go the default way over the accessory.

**Comment by dreamdatcrap** [comment]
Hello,

you understood right. I just wanted to have a switch which lets me turn on and off the oscillation. I do not have any buttons like in the mihomeapp for the oscillation degrees. 

Set up at the moment: 

fan on/off
Nature on/off
Standard on/off

Wanted: oscillation on/off (better with preset degrees)

**Comment by merdok** [comment]
The oscillation enable/disable is implemented on the fan accessory. Just go to devices -> Long press the fan accessory and scroll down. There is a witch for that.

**Comment by dreamdatcrap** [comment]
There is just this round blue button (in HomeKit) which seem so be the fan rotation not the oscillation

If i longierst the fan in HomeKit it gives me my configured switches from the HB. At the moment its fan on/off nature and standard. 

Pressing this round button changes the direction to the error in the button and switches e.g. nature off standard on. Or Standart off nature on (depends on the this which are selected.

Anything to change in HomeBridge??

![1ABA0C90-E9AE-4F39-A1F8-9ED4A9ACA4B2](https://user-images.githubusercontent.com/67903814/86590466-f3d0d700-bf8f-11ea-93d4-a306db9d7dff.jpeg)

**Comment by merdok** [comment]
This is the group which you are on right now. Scroll more down and you will arrive at the settings where you are able to view the devices in that group. There you can long press on the fan accessory to display additional configuration.

And yes, the blue rotation button can also be used to switch between standard and natural mode.

![image](https://user-images.githubusercontent.com/730197/86592419-bbcb9300-bf93-11ea-89ff-7266c8c0d58f.jpeg)

**Comment by merdok** [comment]
You can now press on an active angle to disable oscillation mode.
