### ISSUE TITLE
Any reason why moving support for dmaker.fan.p5 has been removed?

### ISSUE THREAD

**Issue by sw2719** [merdok/homebridge-xiaomi-fan#16]
I initially was going to contact you directly but ehh it's not that serious problem anyway so GitHub issue it is. In version 0.9.5, moving left or right was fully working for dmaker.fan.p5. Then in version 1.0.0, you've removed the feature completely for dmaker fans. I saw that you rewrote and split the code to smartmi and dmaker fans, so I wonder if this is a temporary thing or it's gonna stay this way? I actually had downgraded to 0.9.5 because of this, but then I just modified the code a bit and it works now at least for me.

**Comment by merdok** [comment]
Oh, was that working on the p5? I thought it doesn’t work so I removed it. When it indeed was working then I will add it back. So you can confirm that it was working?

**Comment by sw2719** [comment]
Yeah.

```js
  async moveLeft() {
    return this.sendCommand('m_roll', 'left');
  }

  async moveRight() {
    return this.sendCommand('m_roll', 'right');
  }
```

This works for p5.

**Comment by merdok** [comment]
Sorry for that😅 Somehow I thought this was not working. I will fix that later today with an update! Thanks for letting me know!

**Comment by merdok** [comment]
Move control is now back for dmaker fans in version 1.0.1
