### ISSUE TITLE
Move control not working

### ISSUE THREAD

**Issue by wapster182** [merdok/homebridge-xiaomi-fan#18]
I read the move control was added back, but with latest version 1.0.2 if I press the switches nothing happens.

**Comment by jsiegenthaler** [comment]
Move control works for me on model zhimi.fan.za3 firmware 1.0.2 (bought and installed today), as long as oscillation mode is off.

**Comment by wapster182** [comment]
You are absolutely right! Somehow the oscillation trigger was on, but fan was not moving. I disabled the trigger and now it works perfectly!
Thank you.

**Comment by merdok** [comment]
Yes, you only can use the move control when the oscillation is off. It does not make sense when the oscillation is on to move the fan...

**Comment by wapster182** [comment]
Absolutely.
Can we get a switch just for oscillation? At the moment I always need to go in the main fan object, right?

**Comment by merdok** [comment]
Well I actually did not want to duplicate stuff. Right now the oscillation is implemented like on a native fan device and for that you always have to go on the device to enable or disable that.

**Comment by lorenzhs** [comment]
Wouldn't it make more sense if turning off one of the angle toggles would disable oscillation mode? That's what I was expecting to happen, and it took me quite a while to figure out that I needed to go into the main fan tile and disable it there.

**Comment by wapster182** [comment]
Hi Lorenz, I agree with you! I tried to make this working by configuring an angle button with 0 degree angle. Well, it somehow works: The fan will stop oscillating. If you push it it will get in the straight position, BUT for the fan the oscillation trigger is still on! This means, the left/right move buttons are not working! This was the way I thought it is not working anymore and the purpose of this thread.

**Comment by lorenzhs** [comment]
That’s exactly what I tried at first, too, until I found that I need to manually disable oscillating mode. Glad I’m not the only one ;)

**Comment by merdok** [comment]
I also find that the official oscillation toggle is pretty hidden, i think that the groups which the Home app auto creates makes this even harder to find. 
The idea with the angle switch to turn off the oscillation mode is actually pretty good. I will experiment with that and see if i can somehow come up with something here.
Pressing an angle button would then automatically enable the oscillation mode and the selected angle. And then turning off the switch with the currently active angle would then disable the oscillation mode. That would make sense i think.

**Comment by merdok** [comment]
The angle buttons can now disable/enable the oscillation as of version 1.1.0

**Comment by jsiegenthaler** [comment]
Thanks, that makes sense

**Comment by wapster182** [comment]
Using the version 1.1.3 now, the changes are very great! Love it so far.
