### ISSUE TITLE
dmaker.fan.1c connection error

### ISSUE THREAD

**Issue by baschdie** [merdok/homebridge-xiaomi-fan#20]
Hi,
I'm trying to add the Xiaomi Smart Fan 1c, but I get the following error message in the homebridge log:

_[7/10/2020, 22:26:08] [My Xiaomi Fan] [My Xiaomi Fan] Connected to Fan dmaker.fan.1c
[7/10/2020, 22:26:08] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.1c,
  types=miio,
  capabilities=
}
(node:23589) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:23589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)_

Is it because he is not supported or is there any other reason.

thanks
baschdie

**Comment by BigKrisch** [comment]
Hello,

I get a similar error message with the model zhimi.fan.za4:


Jul 11 08:45:52 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:45:52] [Schlafzimmer Ventilator] MiioDevice {
Jul 11 08:45:52 Raspberry-Homebridge homebridge-mi-fan[10673]:   model=zhimi.fan.za4,
Jul 11 08:45:52 Raspberry-Homebridge homebridge-mi-fan[10673]:   types=miio,
Jul 11 08:45:52 Raspberry-Homebridge homebridge-mi-fan[10673]:   capabilities=
Jul 11 08:45:52 Raspberry-Homebridge homebridge-mi-fan[10673]: }
Jul 11 08:45:57 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Error: Call to device timed out
Jul 11 08:45:57 Raspberry-Homebridge homebridge-mi-fan[10673]:     at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
Jul 11 08:45:57 Raspberry-Homebridge homebridge-mi-fan[10673]:     at listOnTimeout (internal/timers.js:549:17)
Jul 11 08:45:57 Raspberry-Homebridge homebridge-mi-fan[10673]:     at processTimers (internal/timers.js:492:7)
Jul 11 08:45:57 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 484)
Jul 11 08:46:04 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Error: Call to device timed out
Jul 11 08:46:04 Raspberry-Homebridge homebridge-mi-fan[10673]:     at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
Jul 11 08:46:04 Raspberry-Homebridge homebridge-mi-fan[10673]:     at listOnTimeout (internal/timers.js:549:17)
Jul 11 08:46:04 Raspberry-Homebridge homebridge-mi-fan[10673]:     at processTimers (internal/timers.js:492:7)
Jul 11 08:46:04 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 485)
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:11] [Schlafzimmer Ventilator] [Schlafzimmer Ventilator] Connected to Fan zhimi.fan.za4
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:11] [Schlafzimmer Ventilator] MiioDevice {
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]:   model=zhimi.fan.za4,
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]:   types=miio,
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]:   capabilities=
Jul 11 08:46:11 Raspberry-Homebridge homebridge-mi-fan[10673]: }
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:15] [Schlafzimmer Ventilator] [Schlafzimmer Ventilator] Connected to Fan zhimi.fan.za4
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:15] [Schlafzimmer Ventilator] MiioDevice {
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]:   model=zhimi.fan.za4,
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]:   types=miio,
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]:   capabilities=
Jul 11 08:46:15 Raspberry-Homebridge homebridge-mi-fan[10673]: }
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:21] [Schlafzimmer Ventilator] [Schlafzimmer Ventilator] Connected to Fan zhimi.fan.za4
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]: [2020-7-11 8:46:21] [Schlafzimmer Ventilator] MiioDevice {
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]:   model=zhimi.fan.za4,
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]:   types=miio,
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]:   capabilities=
Jul 11 08:46:21 Raspberry-Homebridge homebridge-mi-fan[10673]: }
Jul 11 08:46:23 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Error: Call to device timed out
Jul 11 08:46:23 Raspberry-Homebridge homebridge-mi-fan[10673]:     at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
Jul 11 08:46:23 Raspberry-Homebridge homebridge-mi-fan[10673]:     at listOnTimeout (internal/timers.js:549:17)
Jul 11 08:46:23 Raspberry-Homebridge homebridge-mi-fan[10673]:     at processTimers (internal/timers.js:492:7)
Jul 11 08:46:23 Raspberry-Homebridge homebridge-mi-fan[10673]: (node:10673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the

**Comment by merdok** [comment]
@baschdie dmaker.fan.1c is not supported at the moment. Someone needs to first dump the commands from the fan. This fan uses different commands then the fans before.

@BigKrisch seems like you have some network issues.
