### ISSUE TITLE
Duplicate label in Log Entry

### ISSUE THREAD

**Issue by jsiegenthaler** [merdok/homebridge-xiaomi-fan#23]
The following entry duplicates the label [Fan]. One of them could be removed from the log entry ;)

`[7/14/2020, 16:28:08] [Fan] [Fan] Connected to Fan zhimi.fan.za3`

**Comment by merdok** [comment]
That could be done, yes! I will have a look at it.

**Comment by merdok** [comment]
Fixed in 1.1.4
