### ISSUE TITLE
Why don't you make the oscillating angle a picklist?

### ISSUE THREAD

**Issue by jsiegenthaler** [merdok/homebridge-xiaomi-fan#24]
You currently allow the user to create individual buttons for individual oscillating angles.
This provides for some clutter in the UI.

Have you looked at using e.g. the TV source selection picklist control to allow the user to select one of Off,30°,60°,90° or 120°?

**Comment by merdok** [comment]
The tv source selection picklist is not available to fan accessories.  Besides that with the buttons everyone can individually choose which angles they want to use.
