### ISSUE TITLE
Xiaomi Mi Smart Standing Fan 1C

### ISSUE THREAD

**Issue by terriblefox** [merdok/homebridge-xiaomi-fan#25]
Is it possible to add this ? should be nearly the same as the Smartmi Standing Fan 2S.

https://mi-store.ch/produkt/xiaomi-eco-mi-standing-fan-1c-white-ean-6934177716836/

**Comment by merdok** [comment]
There is already a discussion about that here #13 . The plugin can connect to the fan but unfortunately xiaomi changed the commands again so someone needs to first extract all the commands from the fan. When this is done then adding support for this fan should be pretty straight forward.

**Comment by terriblefox** [comment]
Thx, im jumping over...
