### ISSUE TITLE
Two 2sfans constantly throwing errors

### ISSUE THREAD

**Issue by thorstenman** [merdok/homebridge-xiaomi-fan#28]
I have two Xiaomi 2s fans configured via this great plugin. Unfortunately, the longer my Homebridge is up and running, the more errors ("UnhandledPromiseRejectionWarning") I see in my log. How can I solve this?

**Comment by merdok** [comment]
It would good if you could post a debug log here so i could have a first look if there is something strange there.

**Comment by sw2719** [comment]
Try resetting the fan. Note that you would have to obtain the token again. On the 2s, press two buttons simultaneously for about 5 seconds until you hear beeping sound. If you've added the fan in Mi Home app, you would need to delete the fan and re-add it to use it in Mi Home again.

**Comment by CooperCGN** [comment]
I have the same problem, log attached. Tried starting homebridge with the D parameter but the log then gets spammed with stuff I have no idea what it even is, thousands of slashes.

[log.txt](https://github.com/merdok/homebridge-xiaomi-fan/files/5011347/log.txt)

**Comment by merdok** [comment]
I need a debug log to be able to identify the issue.

**Comment by thorstenman** [comment]
Thanks for asking! And sorry that I was not able to respond earlier. I invested some time now: Deleted the fans from the Homebridge, deleted the plugin, reinstalled and currently reconfigure. Fan 1 is working now without problem, fan 2 can (so far) not be controlled via Apple Home (works in Xiaomi Mi app). Will check with more time - and let you know.

**Comment by merdok** [comment]
You need to make sure that you have the correct token for the other fan.

**Comment by thorstenman** [comment]
Tokens checked - both are correct. Getting this message:

config.json looks like this:
    "platforms": [
        {
            "devices": [
                {
                    "name": "Fan 1",
                    "ip": "x.x.x.x",
                    "token": "xxx",
                    "pollingInterval": 5,
                    "moveControl": true,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeButton": true,
                    "shutdownTimer": false
                },
                {
                    "name": "Fan 2",
                    "ip": "x.x.x.x",
                    "token": "xxx",
                    "pollingInterval": 5,
                    "moveControl": true,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeButton": true,
                    "shutdownTimer": false
                }
            ],
            "platform": "xiaomifan"
        }
    ]

**Comment by thorstenman** [comment]
journalctl -o cat -n 500 -f -u homebridge | grep xiaomi
[2020-8-2 16:46:30] Loaded plugin: homebridge-xiaomi-fan@1.3.1
[2020-8-2 16:46:30] Registering accessory 'homebridge-xiaomi-fan.xiaomifan'
[2020-8-2 16:46:30] Registering platform 'homebridge-xiaomi-fan.xiaomifan'
[2020-8-2 16:46:31] [xiaomifan] Initializing xiaomifan platform...
[2020-8-2 16:46:31] [xiaomifan] Init - initializing devices
[2020-8-2 16:46:31] [xiaomifan] Init - initializing device with name: Fan 1
[2020-8-2 16:46:31] [xiaomifan] Init - initializing device with name: Fan 2
[2020-8-2 16:46:33] [xiaomifan] [Fan 2] Found Fan zhimi.fan.za4
[2020-8-2 16:46:33] [xiaomifan] [Fan 2] Fan total use time: 11350 minutes.

**Comment by merdok** [comment]
Ok, then I would need a debug log. The log which you posted is the default info log.

**Comment by thorstenman** [comment]
Ah ok. Log means an excerpt of /var/log/syslog e.g. using cat /var/log/syslog | grep xiaomi?

**Comment by sw2719** [comment]
Launch homebridge with -D parameter. Also, how are you running homebridge? As a service or what?

**Comment by merdok** [comment]
@thorstenman 
as mentioned by @sw2719 you have to start homebridge with the -D parameter as specified here:
https://github.com/merdok/homebridge-xiaomi-fan#troubleshooting

This will log additional information which can help me to identify the issue.

**Comment by thorstenman** [comment]
Log was completely unaffectious... I reinstalled Homebridge and added the fans from scratch. Now it is working. Thanks!

**Comment by CooperCGN** [comment]
Why are you closing a case obviously not only you have problems with? Will provide log tomorrow, I still get that error.

**Comment by sw2719** [comment]
@CooperCGN Then open a new issue. Your problem is different than the author's if author's solution didn't work.

**Comment by thorstenman** [comment]
I had the same issue again: Why so ever my router gave the fan a new IP (although this is fixed in the network settings) maybe when disconnecting the fan from the power plug and using it temporarily in battery mode. 

Changing the IP in the Homebridge plugin settings did not help, deleting and adding the config again also not as well as deleting and reconfiguring the plugin with two fans. No solution... I now deleted the not accessible fan (Fan2) from Apple HomeKit in Apple's app. The other one (Fan1) is still there and usable. Adding the second one again seem to work - no error messages in the log. 

But unfortunately I can not add the device to Apple HomeKit in the app. You have an idea here how I can add it? How can I reinitiate the painting of the Homebridge device to my Apple HomeKit?

Log looks good and shows no hint:
Aug 04 11:47:15 HomeBridge homebridge[6969]: [2020-8-4 11:47:15] Loaded plugin: homebridge-xiaomi-fan@1.3.1
Aug 04 11:47:15 HomeBridge homebridge[6969]: [2020-8-4 11:47:15] Registering accessory 'homebridge-xiaomi-fan.xiaomifan'
Aug 04 11:47:15 HomeBridge homebridge[6969]: [2020-8-4 11:47:15] Registering platform 'homebridge-xiaomi-fan.xiaomifan'

Aug 04 11:47:15 HomeBridge homebridge[6969]: [2020-8-4 11:47:15] [xiaomifan] Initializing xiaomifan platform...

Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] [xiaomifan] Init - initializing devices
Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] [xiaomifan] Init - initializing device with name: Fan1
Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] [xiaomifan] Init - initializing device with name: Fan2

Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] Ventilator Fan1 is running on port 12345.
Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] Please add [Fan1] manually in Home app. Setup Code: xxx-xx-xxx
Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] Fan2 is running on port 23456.
Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] Please add [Fan2] manually in Home app. Setup Code: xxx-xx-xxx

Aug 04 11:47:16 HomeBridge homebridge[6969]: [2020-8-4 11:47:16] [xiaomifan] [Fan2] Found Fan zhimi.fan.za4

Aug 04 11:47:17 HomeBridge homebridge[6969]: [2020-8-4 11:47:17] [xiaomifan] [Fan1] Found Fan zhimi.fan.za4
Aug 04 11:47:17 HomeBridge homebridge[6969]: [2020-8-4 11:47:17] [xiaomifan] [Fan2] Fan total use time: 11910 minutes.
Aug 04 11:47:18 HomeBridge homebridge[6969]: [2020-8-4 11:47:18] [xiaomifan] [Fan1] Fan total use time: 11755 minutes.

**Comment by merdok** [comment]
The log which you posted here seems perfectly fine.

You need to keep in mind that when you run your fan on battery and it is not plugged in, then it will go into sleep mode after around 2 hours. After that it disabled the WiFi and you will not be able to control it anymore unless you turn it on manually using the button on the device.

To add a fan to your home app please follow the guide in the README.

**Comment by thorstenman** [comment]
Thanks, what you wrote is clear to me. I followed the instructions on how to add bit the fan does not show up. 

Seems so that Homebridge thinks that the device is still linked. But it is not visible in the HomeKit app... can I manually activate the internal processing to reconnect it?

**Comment by merdok** [comment]
You can try to change the name of the fan, besides that you would need to delete your cached accessories in homebridge.

**Comment by thorstenman** [comment]
That worked. Great! Thanks, @merdok for your help!
