### ISSUE TITLE
Understandable models 

### ISSUE THREAD

**Issue by stijndevries** [merdok/homebridge-xiaomi-fan#29]
Hi, 

Thanks for working on this plugin! 
It would be great if marketing names (like 2S or 1C) could be added behind the technical names in the readme. That would be good for discoverability and for knowing which fan to buy. I for example am looking to buy a comparable fan but I can't find anything with these technical names.

Stijn

**Comment by merdok** [comment]
True, that could be done. I will see if i can add that in the next update

**Comment by sw2719** [comment]
Here's all I know :

Supported fans:
zhimi.fan.za1: Smartmi Fan (2nd gen)
zhimi.fan.za3: Smartmi Fan 2
zhimi.fan.za4: Smartmi Fan 2s
zhimi.fan.sa1: Mijia DC Inverter Fan
dmaker.fan.p5: Mijia Fan 1X

Not supported / Unknown fans:
zhimi.fan.v2/zhimi.fan.v3: Smartmi Fan (1st gen)
zhimi.fan.za5: Smartmi Fan 3
dmaker.fan.p10: Mijia 2-in-1 DC Inverter Fan 2
dmaker.fan.p9: Mijia Tower Fan
dmaker.fan.1c: Mijia Fan 1C

**Comment by merdok** [comment]
@sw2719 hmmm i think it should be like that:
zhimi.fan.za1: Smartmi Fan 
zhimi.fan.za3: Smartmi Fan 2
zhimi.fan.za4: Smartmi Fan 2S

**Comment by merdok** [comment]
Added in version 1.2.0
