### ISSUE TITLE
Switches are still displayed

### ISSUE THREAD

**Issue by BigKrisch** [merdok/homebridge-xiaomi-fan#3]
Hello Merdok,

first of all many thanks for this great plugin!! 👍👏

But I noticed the following. If the value "false" is entered in the config.json for BuzzerControl, LEDControl and MoveControl, the respective switches in the HomeApp are still loaded.

Only when I have changed the stand values in Index.js to "false" they are no longer displayed in the HomeApp. 

If this is an error or if I have set the configuration wrong.

Thank you very much for your help!

**Comment by merdok** [comment]
The value is not a string so you should leave the " (quotas) out. It should be like:
`"ledControl": false`

**Comment by BigKrisch** [comment]
So it is also registered with me in the config.json. The entry was created via config-ui-x.
Enclosed my current configuration. 

> {

            "name": "Wohnzimmer Ventilator",
            "ip": "192.168.XXX.XXX",
            "token": "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "prefsDir": "~/.xiaomiFan",
            "pollingInterval": 5,
            "moveControl": true,
            "buzzerControl": false,
            "ledControl": false,
            "accessory": "xiaomifan"
        }

**Comment by merdok** [comment]
Yes, this looks good and should work as expected. Does it work with the config above?

**Comment by BigKrisch** [comment]
No, I'm afraid it's not working. 
The additional switches are not hidden until I set the default values in the Index.js to false.

**Comment by merdok** [comment]
You are right, there is a bug. I will fix this. Thanks for letting me know!

**Comment by BigKrisch** [comment]
Perfect!
Thank you very much. 👍

**Comment by merdok** [comment]
Fixed in version 0.8.1. Please try it and let me know if it works now.
