### ISSUE TITLE
buzzerControl with rotation direction switch not working on Xiaomi Smartmi Fan 2S (zhimi.fan.za4)

### ISSUE THREAD

**Issue by MichlW** [merdok/homebridge-xiaomi-fan#31]
I use this plugins for some days now and nearly everything is working very well. Many thanks for your work!
But i have a last one problem with my Xiaomi Smartmi Fan 2S (zhimi.fan.za4) model.

In readme `buzzerControl` is described as:
```
buzzerControl
[optional] Whether the buzzer service is enabled. This allows to turn on/off the fan buzzer.
On Smartmi fans the rotation direction switch can be used to select between loud or quiet buzzer level.
Default: true
```
But no matter if I set this value to true or false, the rotation direction switch (blue circle arrow) in Homekit fan device do not act as buzzerControl switch. If set to true, it just creates a normal switch button that works smoothly.

Am i doing something wrong?

**Comment by merdok** [comment]
You only use the rotation direction switch to switch between loud and quiet mode when your buzzer is enabled. that means the normal switch button needs to be on or the buzzer simply needs to be turned on from the official app.

**Comment by MichlW** [comment]
Thank you very much, that works. I am surprised that this is not described in detail in the official readme.

**Comment by merdok** [comment]
`On Smartmi fans the rotation direction switch can be used to select between loud or quiet buzzer level.`
This line indicated that it is only used to switch between loud and quiet mode, it is not used to turn on/off the buzzer.

**Comment by MichlW** [comment]
Thanks for the clarification. I misinterpreted the word "quiet".

Can the blue circular arrow in principle be hidden in the Home app? I think there are a lot of smart fans that only support one direction of rotation. Is this really what Apple wanted?

**Comment by merdok** [comment]
It can be hidden, but then the layout changes slightly and some users are confused... but I might add a configuration field for that.

**Comment by MichlW** [comment]
That would be great.
With regard to high flexibility for available fans, I think that many would be happy about such an configuration option. Everyone can then decide for themselves whether the layout suits their own taste.

Thanks in advance.

**Comment by ghost** [comment]
Is it possible to map the rotary button to for example nautrual wind mode instead of useleaa buzzer volume? :)

**Comment by merdok** [comment]
@malmentm why would you want to map that which does not exactly tell you which one is active, when you already have the possibility to enable a dedicated switch for that?
