### ISSUE TITLE
Support for HOOBS is gone

### ISSUE THREAD

**Issue by DarkSyler21** [merdok/homebridge-xiaomi-fan#35]
Using the plugin for a few weeks now on HOOBS new version when trying to input the config in the configuration section in plugin page on HOOBS seems to not working at all and shutdown the entire bridge for HOOBS.

**Comment by merdok** [comment]
The plugin switched from an accessory plugin to a platform plugin. That means the config schema also changed to the recommended platform plugin config. You should switch to a platform as soon as possible, check the README or CHANGELOG for that, since I will be removing accessory support soon.

**Comment by DarkSyler21** [comment]
Done all working now thanks for the advice.
