### ISSUE TITLE
Feature request: Move fan x degree left/right from neutral point

### ISSUE THREAD

**Issue by wapster182** [merdok/homebridge-xiaomi-fan#37]
Hi,

I would like to ask if this is possible: I want to have a switch to move the fan exact x degree from neutral point in left or right direction.

With that, I could make switches so automatically align the fan to the desired places, like couch or bed. You could say, "Hey Siri, Fan bed" and it would move to the bed direction.

At the moment you can move it with the switches, but since there is no "neutral point" it is impossible to automate effectively, because the alignment is always different.

Regards

**Comment by merdok** [comment]
Sorry this is unfortunately not possible. There is no api for that. There only way i could think off is that you would need to track the current position and trigger the move left or right switch a number of times till it is at the desired position.
