### ISSUE TITLE
Homebridge Scene with more then one fan controls won‘t work

### ISSUE THREAD

**Issue by Jodameister** [merdok/homebridge-xiaomi-fan#38]
Hello,
i‘ve make a scenes  with fan controls like: 

Scene 1: fan on, rotation speed 40%, natural switch on, shutdown timer off.
Scene 2: fan on, rotation speed 100%, natural switch off, shutdown timer off.

When i switch between these scenes, only the rotation speed is changed. Natural switch is still on. No error logs.

Andy ideas?

**Comment by merdok** [comment]
Well, just tried it out and you are right. I am not sure if this can be fixed or not, this is basically an issue with the order how the home app starts the scene. I will have a look at it and see if there is something that can be done...

**Comment by merdok** [comment]
Should be fixed in version 1.4.0
