### ISSUE TITLE
Timer extension

### ISSUE THREAD

**Issue by Nastras** [merdok/homebridge-xiaomi-fan#4]
Hello,
i don't have your plugin installed yet but will do it soon. Thanks for your work!

I still have an idea for an extension. Is it possible that you install a slider on the device that can be used as a timer for the fan?

Would be pretty cool 😃

**Comment by merdok** [comment]
hi,

that sounds interesting. I will check if that is possible. I am currently not sure how this would exactly work with a slider but i will give it a try.

**Comment by Nastras** [comment]
I was thinking of a slider that can be set in minutes in homekit directly at the fan. But I'm not sure if this is possible. 


Example if this slider is set to 60 the plugin counts 60 minutes backwards and switches off the power switch of the fan.

I was inspired by the plugin homebridge-automation-switches with the function Alarm Clock.
https://github.com/grover/homebridge-automation-switches

**Comment by merdok** [comment]
I need to experiment with this. I am not sure how the slider should behave, like does it have to tick down every minute or what happens if move it when there is already a timer. I mean yes, that would be possible but I am not sure if the control would be intuitive and good...

**Comment by Nastras** [comment]
That's just an idea, maybe there's a better solution than mine.
A timer would be great for the fan if it could be realized.

**Comment by merdok** [comment]
I will think about it and see if i come up with something good.

**Comment by merdok** [comment]
This is not included in version 1.0.0. Sorry it took so long...
