### ISSUE TITLE
using homebridge-xiaomi-fan with iobroker.ham

### ISSUE THREAD

**Issue by entavio** [merdok/homebridge-xiaomi-fan#41]
hey, 

i am using homebridge-xiaomi-fan with iobroker.ham (v2.0) 
as it looks like the plugin works and iobroker.ham gets green.... but i don't get any data set points for mapping into yahka... 

is this plugin only for directly use in HomeKit?!

**Comment by merdok** [comment]
Sorry, I have no idea about iobroker.ham and I really cannot be any help for you with that, the plugin is made to work with homebridge and it works perfectly with it. 
This seems to be some kind of an adapter issue and any issues with the adapter should be directly cleared at the iobroker.ham GitHub. I am not even aware what yahka is...

**Comment by entavio** [comment]
Ok but the Homebridge Adapter works and also your plugin, but I get no datapoints like power on/off or oscillation angle ....

**Comment by merdok** [comment]
I guess the issue that you get no datapoints is not really an issue with this plugin.

**Comment by entavio** [comment]
Yeah looks like that the plugin doesn't generate any data points that can be used by other apps or plugins ..... a shame :-(

**Comment by merdok** [comment]
Then you would need to open an issue at the github page of that other plugin and ask for that there. There is nothing really that i can do it. My plugin a homebridge plugin and not a iobroker plugin, i have nothing to do with iobroker...
I think the dev of iobroker.ham already asked you for some information  as i saw in the other thread over there so i guess you should do that.
