### ISSUE TITLE
Issue with Token on Mi Fan 1C

### ISSUE THREAD

**Issue by stijndevries** [merdok/homebridge-xiaomi-fan#42]
Hi there,

First of, thank you for your work in this plugin! Im having an issue with adding my 1C fan to homekit. If i use the example config  it shows up in the add accessory window but when i change the token to to the one of my fan it doenst show up. I got this token using the device backup and the miIO device library command, both giving the same code. Every token works except for the correct token. 
Log: 
[xiaomifan] Init - initializing devices
[xiaomifan] Init - initializing device with name: Xiaomi Fan 2s
Xiaomi Fan 2s is running on port 45597.

**Comment by stijndevries** [comment]
This is my config inside hoobs:
[
    {
        "name": "Xiaomi Fan 2s",
        "ip": "192.168.178.122",
        "token": "4a50c84321f8d1e7e9b2bb966875537a",
        "pollingInterval": 10,
        "moveControl": false,
        "buzzerControl": true,
        "ledControl": true,
        "naturalModeButton": true,
        "shutdownTimer": true
    }
]

I am using the ios 14 beta.

**Comment by stijndevries** [comment]
This is my config inside hoobs: (token redacted)
[
{
"name": "Xiaomi Fan 2s",
"ip": "192.168.178.122",
"token": "4a50c84321f8d1e7e9b2bb966875----",
"pollingInterval": 10,
"moveControl": false,
"buzzerControl": true,
"ledControl": true,
"naturalModeButton": true,
"shutdownTimer": true
}
]

I am using the ios 14 beta.

**Comment by stijndevries** [comment]
Im getting these errors 
8/4/2020, 4:29:58 PM [xiaomifan] [Xiaomi Fan 1C] Error: Could not connect to device, token might be wrong
8/4/2020, 4:29:58 PM [xiaomifan] [Xiaomi Fan 1C] Fan not found! Retrying in 60 seconds!

My token is definitely correct tough

**Comment by merdok** [comment]
The error log states clearly that the plugin cannot connect to your fan. This can have multiply causes:

- Wrong ip of your fan
- The fan cannot be reached from your network (if you are using multiple networks)
- different sub networks
- the token is wrong

So in general this is a network or token issue.

I would suggest that you double check your fan token and your network. The fan needs to be reachable from your homebridge machine in the network.

**Comment by stijndevries** [comment]
Thank you for your response! I use one wifi network but the devices cant reach each other, when i ping the IP it doesnt connect. Not from my RPi and my macbook. All of my devices are on the same subnet so im not to sure whats causing this.

I am getting different errors tough:
[xiaomifan] [Xiaomi Fan C1] Error: Could not connect to device, handshake timeout
[xiaomifan] [Xiaomi Fan C1] Fan not found! Retrying in 30 seconds!

**Comment by merdok** [comment]
Well, then the issue is related to your network. You will need to find out why your fan is not reachable. You can also install the miio npm package on your raspberry pi and then run `miio discover` command in the terminal, the fan should appear there.

**Comment by stijndevries** [comment]
Okey, im now able to ping it from the Pi and i am able to find the fan with miIO. Still doesnt work. I will take a look if token is the issue with a new backup but i checked that during setup with miIO so i dont think thats it.

**Comment by merdok** [comment]
Sometimes you first need to unplug and plug the 1C back in the electric socket for it to work, especially when you controlled it with the official mi home app before. 

But yeah, if the plugin cannot connect to the fan then it is either the token or a network issue. Both of them are local issues and there is nothing that i can do about it, except recommend to double check the network and token 😉

**Comment by stijndevries** [comment]
I checked it again and its the correct information. I also tried it with a clean install of homebridge on macos, still not working. 

But.....  I now notice this error: [8/4/2020, 7:24:45 PM] [xiaomifan] Xiaomi Fan - fan model info file does not exist

**Comment by stijndevries** [comment]
Okey, i see that that is expected behaviour.

**Comment by merdok** [comment]
Yes, after the plugin connects to the fan for the first time then fan information will be saved and this error will go away.

**Comment by stijndevries** [comment]
Okey, I set up another router with a new network and tried again. Still does not work. Im able to ping and find the fan with miio discover. Is it possible that this is not a local issue?

**Comment by merdok** [comment]
I am pretty sure that this is a local issue. You can try to join the xiaomi-fan discord channel on the homebridge server, we can try to do some live debugging there to identify your issue. Basically the next step would be to try send raw commands to your fan using miio to check if that works.

**Comment by stijndevries** [comment]
That would be great! the button in the readme gives me an invalid invite, is there a new link?

**Comment by merdok** [comment]
Oh, sorry about that. Fixed the button!

**Comment by sw2719** [comment]
Can you use terminal on the RPi? Try this command: ```miio tokens update [your fan's ip] --token [your fan's token]```

**Comment by stijndevries** [comment]
I get this:
```
 INFO  Updating token for 192.168.178.123
 INFO  Connected to miio:240463067  - trying to change token
 ERROR  Could not update token, double-check the given token
```
I just reset the fan and used miso to get the token so its definitely correct.

**Comment by stijndevries** [comment]
This was an issue with my token. I think I made a backup without opening the app to update the token after resetting it.
Fixed now.
