### ISSUE TITLE
Can help me with xiaomi tower fan

### ISSUE THREAD

**Issue by Kennyyys** [merdok/homebridge-xiaomi-fan#47]
Hi, I got the xiaomi tower fan, think is the latest version product, it can be install at my mi home app but I can't see the fan at my Google assistant app as I can see other xiaomi products. Any chance I can control the fan thru Google assistant?

**Comment by merdok** [comment]
This plugin is only for Apple HomeKit, Google Assistant is not and will be not supported!

**Comment by Kennyyys** [comment]
Oh ok, thanks for the quick reply
