### ISSUE TITLE
Xiaomi fan 2S connection problem

### ISSUE THREAD

**Issue by recovery23** [merdok/homebridge-xiaomi-fan#48]
Hello

i have a question to the plugin. I use a xiaomi fan 2S with your plugin and my home App. When the xiaomi is connectet with electricity it works. But when the xiaomi is without electricity it canceled the connection to wifi after a time and get sleeping. after that i can not use it with the home app. I have to torn on it with the button. only then he connectec again with the wifi and with the xiaomi app but not with the home app. i have to restart the homebridge. what is the fail?

here my config
            "devices": [
                {
                    "name": "Ventilator",
                    "ip": "192.168.178.51",
                    "token": "eb...............................be98",
                    "pollingInterval": 10,
                    "moveControl": true,
                    "buzzerControl": false,
                    "ledControl": true,
                    "naturalModeButton": true,
                    "shutdownTimer": true,
                    "angleButtons": [
                        30,
                        90,
                        120
                    ]
                }
            ],
            "platform": "xiaomifan"

**Comment by merdok** [comment]
The fan is designed like that by xiaomi. When it is on battery then the device will go sleep in order to preserve battery, in that case you have to turn it on manually to be able to control it again. To prevent that you can leave it all the time plugged in.

**Comment by recovery23** [comment]
HI yes but that's my problem when I turn it on manually it works in the xioami app but not in the home app

**Comment by merdok** [comment]
It takes some time for the fan to work in the home app again. You cannot instantly control it after turning it on.

**Comment by recovery23** [comment]
Hi thanks, I have let it run for several hours but it is not recognized.
Only when I restart the Homebridge does it work again immediately.

**Comment by merdok** [comment]
What does the debug log say?

**Comment by recovery23** [comment]
HI have now gone through the daemon log, but unfortunately I find almost nothing to fan these are the only things about it

Aug 26 19:24:40 raspberrypi homebridge[21337]: [2020-8-26 19:24:40] [xiaomifan] Init - initializing devices
Aug 26 19:24:40 raspberrypi homebridge[21337]: [2020-8-26 19:24:40] [xiaomifan] Init - initializing device with name: Ventilator
Aug 26 19:24:40 raspberrypi homebridge[21337]: [2020-8-26 19:24:40] Ventilator is running on port 35855.
Aug 26 19:24:40 raspberrypi homebridge[21337]: [2020-8-26 19:24:40] Please add [Ventilator] manually in Home app. Setup Code: XXXXXX
Aug 26 19:24:41 raspberrypi homebridge[21337]: [2020-8-26 19:24:41] [xiaomifan] [Ventilator] Found Fan zhimi.fan.za4
Aug 26 19:24:41 raspberrypi homebridge[21337]: [2020-8-26 19:24:41] [xiaomifan] [Ventilator] Fan total use time: 1405 minutes.

Shouldn't he normally also record something when you press a button in Home?

**Comment by merdok** [comment]
Yes, in debug mode. You need to start homebridge in debug mode.

**Comment by recovery23** [comment]
HI have now run it in debug mode for a few hours.
Do you need the complete log or just certain things?

**Comment by merdok** [comment]
Just try to control the fan while in debug mode and post the log.

**Comment by recovery23** [comment]
HI have now tried to copy what I found out of the log.
If it is not enough I can send you the complete log file
https://www.dropbox.com/s/73us0lo185713mm/Log.rar?dl=0

**Comment by merdok** [comment]
I do not see you trying to control  the fan in that log? Did you try to control the fan?

**Comment by recovery23** [comment]
HI pressed the commands several times.
Send them the complete log

https://www.dropbox.com/s/lg9z5p1f0sxpu7x/daemon.rar?dl=0

**Comment by merdok** [comment]
This is not a homebridge debug log which you posted. See here on how to do a correct debug log: https://github.com/merdok/homebridge-xiaomi-fan#troubleshooting

**Comment by recovery23** [comment]
HI hope this is the right log now :)
https://www.dropbox.com/s/mbr4lfjc89t3jyr/homebridge.log?dl=0

**Comment by merdok** [comment]
This is still not a homebridge debug log...

**Comment by recovery23** [comment]
HI have now asked again in the forum how exactly it works with the debug.
Then someone told me that if you were in the debug, The Homebridge would write your entire card in about 5-10 minutes.
The problem is that I have to wait about 2-3 hours for the fan to go into standby bye.
So I'll leave it anyway, thank you for your time

**Comment by merdok** [comment]
All right, if the issue will reappear or you have a proper debug log then just let me know. For know i will close this issues.
