### ISSUE TITLE
shutdownTimer

### ISSUE THREAD

**Issue by Nastras** [merdok/homebridge-xiaomi-fan#51]
Hello @merdok ,

i wanted to ask if it is not possible to set the slider as an individual feature instead of as a light if you don't need it in your home app?
Find it a little confusing for the woman as a lamp :-)

Maybe you can use the config to allow you to choose how to display it?

Thanks!

Regards
Nastra

**Comment by merdok** [comment]
Hi,

there is honestly no other way to show a shutdown timer in HomeKit. HomeKit does not support officially custom configurable shutdown timers so i had to "hack" it in using a lightbulb 😜  I mean if you have a better idea then showing a lightbulb then feel free to let me know and i will see 😉

**Comment by Nastras** [comment]
I'm not the expert, but as far as I know there are user defined features that can be added to a device. A slider should also be possible.

This plugin uses such a slider for a switch, maybe you can see something in the code?

https://github.com/hans-1/homebridge-cmdtriggerswitch

**Comment by Nastras** [comment]
Like this:
![Switch-02](https://user-images.githubusercontent.com/27686185/94152671-22b66500-fe7c-11ea-837e-c4f9767d3001.png)

**Comment by merdok** [comment]
This is not the Home app. You are showing me the Eve app which has custom controls for their own devices.  When you look at the switch in the Home app then what do you see there?

**Comment by Nastras** [comment]
I also meant whether it is possible to select in the Config whether the slider is shown as a custom control. The custom controls are not exclusively in the eve app. Every third party app does not show them, only the home app.

I think we have misunderstood each other? .-)
But if you say that it is not possible is of course not that bad.

**Comment by Nastras** [comment]
I just looked again and this plugin uses the same possibility as I thought:

**Comment by merdok** [comment]
I only use controls which are available in the Home app since most of the people use that. Also the control which you provided on the screenshot above is not ideal for a shutdown timer...
I think a lightbulb is at this point the best solution for a shutdown timer.

**Comment by Nastras** [comment]
So my question is whether you can add an option in config.json that allows you to specify whether the shutdown timer is shown as a light bulb or as the variant I showed you?

So every user would have the choice as he wants to have it.

**Comment by merdok** [comment]
I cannot add such option because the variant which you showed is not supported in the Home app. The Eve app has a lot custom made controls which they use for their own devices, those custom controls are not supported in the Home app. As soon as Apple provides new controls which can be used in the Home app then i can change that, but for now unfortunately it has to be emulated as a lightbulb...

**Comment by Nastras** [comment]
All right. I will close the issue here for now. If the situation changes we can open it here again.

Thanks a lot anyway.
