### ISSUE TITLE
Crash since Update

### ISSUE THREAD

**Issue by philmue1988** [merdok/homebridge-xiaomi-fan#53]
Hi all

since the update, the plugin seems to be crashed. I deinstalled and installed it again put it is not possible to insert the data. Does anybody also have the same issue?

**Comment by merdok** [comment]
What fan do you have? Can you provide a homebridge debug log?

**Comment by philmue1988** [comment]
i already de-installed it but there was standing that "my fan" is not registered by any plugin. I also tried to install it on my other homebridge and it is not working. I´m not able to add a fan in the userinterface of the homebridge 

![Uploading Bildschirmfoto 2020-10-02 um 15.44.12.png…]()

**Comment by merdok** [comment]
You still did not provide any fan information or debug log. In order for me to at least have a small idea of what is happening on your side I need those info...

**Comment by philmue1988** [comment]
here there is my debug log as well as the config info.

 [10/2/2020, 16:01:27] Loading 2 accessories...
Oct 02 16:01:27 raspberrypi homebridge[5609]: [10/2/2020, 16:01:27] Error loading accessory requested in your config.json at position 1
Oct 02 16:01:28 raspberrypi homebridge[5609]: [10/2/2020, 16:01:28] Error: The requested accessory 'xiaomifan' was not registered by any plugin.
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Array.forEach (<anonymous>)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Oct 02 16:01:28 raspberrypi homebridge[5609]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Oct 02 16:01:28 raspberrypi homebridge[5609]: [10/2/2020, 16:01:28] Got SIGTERM, shutting down Homebridge...
Oct 02 16:01:33 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Oct 02 16:01:33 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Oct 02 16:01:33 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Oct 02 16:01:43 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Oct 02 16:01:43 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Oct 02 16:01:43 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Oct 02 16:01:44 raspberrypi homebridge[5746]: [10/2/2020, 16:01:44] Loaded config.json with 2 accessories and




{
            "name": "Ventilator Schlafzimmer",
            "ip": "192.168.0.XXX",
            "token": "047b14b1fa5538a8c75XXXXXcf5557063",
            "pollingInterval": 5,
            "moveControl": true,
            "buzzerControl": false,
            "ledControl": false,
            "naturalModeButton": true,
            "shutdownTimer": false,
            "accessory": "xiaomifan"
        },

**Comment by philmue1988** [comment]
Fans are FAn1X and 2S

**Comment by merdok** [comment]
Thanks! Now i can tell you that your config is wrong. You are trying to configure the plugin as an accessory, but you need to configure it as a platform. Please have a look at the example config in the README.

**Comment by philmue1988** [comment]
but this is new right? Because i didnt change anything and before the update everything was fine

**Comment by merdok** [comment]
Yes, as stated in the CHANGELOG, the possibility to configure the plugin as an accessory has been removed in the latest update. This is because i need to support many different fans with different features and this is only possible when the plugin runs as a platform.

**Comment by philmue1988** [comment]
okay thank you now its working again! Thanks
