### ISSUE TITLE
Settings not displayed on Config UI

### ISSUE THREAD

**Issue by h0mesmart** [merdok/homebridge-xiaomi-fan#54]
Hello, 
since v.1.4.0, impossible to configuring the plugn with homebrige UI 

And the config before the update is not read by the plugn,
![Screenshot 2020-10-02 at 15 00 47](https://user-images.githubusercontent.com/64425114/94925885-38e9a400-04c0-11eb-9fbe-a266c0b0e17a.png)

Here is my config 
{
            "platform": "xiaomifan",
            "devices": [
                {
                    "name": "Vito",
                    "ip": "10.0.0.131",
                    "token": "xxxxxxx",
                    "pollingInterval": 10,
                    "moveControl": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "naturalModeButton": false,
                    "shutdownTimer": false
                },
                {
                    "name": "Ventilateur",
                    "ip": "10.0.0.135",
                    "token": "xxxxxxx",
                    "pollingInterval": 10,
                    "moveControl": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "naturalModeButton": false,
                    "shutdownTimer": false
                }
            ]
        },

and here is what I see in accessories 

![Screenshot 2020-10-02 at 15 04 13](https://user-images.githubusercontent.com/64425114/94926117-8fef7900-04c0-11eb-8b77-c9cc6eaf7804.png)

I see a lot of switch toggle !!! 

Please Help

FYI I have mi fan 2s, homebridge 1.2.3, Homebridge-config-ui-x v4.28.0

Thanks

**Comment by merdok** [comment]
Will check out the ui config later today.
There are a couple of new switches based on what fan you are using, those can be disabled in the config. Just check the README -> configuration for details.

**Comment by h0mesmart** [comment]
Config modified manually, indeed the new swtiches need to be disabled.

**Comment by merdok** [comment]
Ui config should be fixed in version 1.4.1

**Comment by h0mesmart** [comment]
great, everything back to normal. Thank you
