### ISSUE TITLE
AngelButtons still appear in HomeApp after rmoving them

### ISSUE THREAD

**Issue by Spy-1** [merdok/homebridge-xiaomi-fan#56]
If you set the parameter "AngelButtons" and remove it at some point, the buttons will still be displayed in HomeApp. Even after a restart of Homebridge or Pi.

**Comment by merdok** [comment]
You need to leave the property in but set an empty array as the value []. This should make them disappear.

**Comment by Spy-1** [comment]
Thanks for your quick reply. I tried this but nothing changed.

**Comment by merdok** [comment]
Hmm, should actually work. I will check that out and see if that is a bug.

**Comment by merdok** [comment]
Should be fixed in version 1.4.3. I also updated the README to clarify that more! Please let me know if the issue is fixed!

**Comment by Trippersgarage** [comment]
I've tested it with the empty array value and it works now. Nice.

**Comment by merdok** [comment]
Good to hear. Then I think that this can be closed. Thanks!
