### ISSUE TITLE
Set Angle switches to OFF when fan is turned OFF

### ISSUE THREAD

**Issue by jsiegenthaler** [merdok/homebridge-xiaomi-fan#58]
In iOS14, all switches set to ON show up in the Home overview, which includes the Xiaomi Fan Angle switch, even when the fan is turned OFF
This means I can never have a house where all switches are OFF.
I often check everything is turned off before I go to bed: but with the Xiaom fan I can never achieve an all-off status.

Could you adapt the plugin so that when the fan is turned OFF, all the Angle switches also go to OFF?
And then when the fan is turned ON, the last used Angle switch is turned back ON?

That would be a much better fit to the new iOS 14 Home app.

**Comment by merdok** [comment]
Thanks for the feedback. This is a completely valid suggestion and i think that you are right. If the fan is turned off then the angle buttons should also be kept off. I did that change in version 1.4.3. Please let me know if it works as desired now for you.

**Comment by jsiegenthaler** [comment]
I do believe I never replied back that it was now good. So here is that reply. The fan is now properly shown as all switches are OFF when I have turned the fan off. Thanks for the changes 

I'll close this issue

**Comment by jsiegenthaler** [comment]
Fixed. Thanks

**Comment by merdok** [comment]
Thanks for closing and letting me know :)
