### ISSUE TITLE
Controlling with Siri?

### ISSUE THREAD

**Issue by david-levi** [merdok/homebridge-xiaomi-fan#59]
Hi, first of all, thanks for all the hard work! This plugin is amazing.

I'm having some trouble controlling my fan (Mi Smart Standing Fan 1C) through Siri. I can turn it on and off, but that's about it. Telling Siri to "set fan speed to high/medium/low" doesn't work, and telling it to "turn on fan level 1/2/3" (as it appears in Home) actually sets the shutdown timer percentage.

1) Can you please share some Siri commands that you know are working? Maybe I am approaching this wrong.
2) Do you think it's possible for the plugin to use a Fan Speed control (like in [this photo](https://i0.wp.com/9to5mac.com/wp-content/uploads/sites/6/2019/03/Lutron-HomeKit-fan-switch.jpg)) instead of separate "level" switches? You could maybe map certain ranges to a speed level (1-33 to Level 1, 34-66 to Level 2, 67 to 100 to Level 3, etc.)

Thanks.

**Comment by merdok** [comment]
Hi,

thanks for the feedback.
For your points:
1. Well, you have to exactly say the name of the switch in order for Siri to work, in case Siri does not understand you try to rename the switch.
2. Well, the point is that the dmaker fan 1c does not support free fan speed control. It only supports those 3 predefined level. Putting a slider in would just confuse users and that could lead to unnecessary opened issues. Actually it was already like you said with an emulated slider before as a hack, but that was recently changed by me to a correct implementation. The ultimate goal is to easily support all kind of fans in the future and for that i do not want to do fan specific hacks anymore...
