### ISSUE TITLE
HOOBS removes the line with an empty array for angleButtons

### ISSUE THREAD

**Issue by OlehProkopenko** [merdok/homebridge-xiaomi-fan#60]
hw: dmaker.fan.p9 (Mi Smart Tower Fan)
sw: HOOBS 3.2.6
After update to 1.4.3 I tried to hide all the angle buttons but when I create the angleButtons key with an empty array 
`"angleButtons": [] `
and press the save button, the line disappears and all angle buttons are shown in the Home app. All other keys can be added without any issues.

**Comment by merdok** [comment]
This is pretty stupid that it gets removed without your intention...
Anyway you can try to set it to [""] or false. That should also remove them.

**Comment by OlehProkopenko** [comment]
> This is pretty stupid that it gets removed without your intention...
> Anyway you can try to set it to [""] or false. That should also remove them.

`false` -> works without any issues
`[""]` -> works but device status is shown as not responding despite it is possible to turn the fan ON/OFF

**Comment by merdok** [comment]
Good to hear! Then I guess the issue can be closed.
