### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DarkSyler21** [merdok/homebridge-xiaomi-fan#61]
Hi,
thanks for all the work on the Plugin works great on HomeBridge!
wanted to ask if its possible to make it available to choose Fan icon on HomeKit instead of the regular low standing fan (I'd like the option to choose long standing fan)
thanks!

**Comment by merdok** [comment]
Hi,

I know what you mean, but I am not sure if I have control over that. I already once tried to adjust that but there does not seems any way to control that from my side. Not really sure what the home expects to make the icon configurable...

**Comment by DarkSyler21** [comment]
with other plugins I use it works very well for lights so that's why I asked.
Thanks for the explanation anyway maybe someday apple will let us know how to do so lol.

**Comment by merdok** [comment]
I know it works for other plugins, but other plugins also do not do anything special, it just works. I also know that there are different fan icons I just do not know how to show them and if this is even possible. I will remember that and check it out and hopefully find a way in the future.
For now I close the issue.
