### ISSUE TITLE
MiFan 2S - Impossible to control the fan via Home app or HB accessory Tab

### ISSUE THREAD

**Issue by h0mesmart** [merdok/homebridge-xiaomi-fan#62]
Hello There, 

Since v.1.4.3, I do have a strange issue. 
I cannot control the fan thru Home app. The thing is in home app the device  is available, i mean it  do not show no response. But as soos as you hit the tile to turn the fan on, the tile show no response with ! . 
The only way to get it works again is to restart homebrigde. After the restart It's working for a while, but cannot tell how long as I did not use the Fan as much as during summer. But I have a scene which turn on and off the Fan in the morning, so every morning the scene failed, and I have to restart homebridge every morning. It's a bit to much :( 
Could you help me please. 

Here is my config : 

Homebridge : v1.2.3 installed on a Pi 3b+
Homebridge config ui :  v 4.29
node.js : v12.19.0
npm : v6.14.8
xiaomi fan plugin : v 1.4.3

   {
            "devices": [
                {
                    "name": "Vito",
                    "ip": "10.0.*.*",
                    "token": "**************************",
                    "pollingInterval": 5,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "naturalModeControl": false,
                    "sleepModeControl": false,
                    "moveControl": false,
                    "shutdownTimer": false,
                    "ioniserControl": false,
                    "fanLevelControl": false
                },
                {
                    "name": "Ventilateur",
                    "ip": "10.0.*.*",
                    "token": "**************************",
                    "pollingInterval": 5,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "naturalModeControl": false,
                    "sleepModeControl": false,
                    "moveControl": false,
                    "shutdownTimer": false,
                    "ioniserControl": false,
                    "fanLevelControl": false
                }
            ],
            "platform": "xiaomifan"
        },

Here attache the log file of today
[HBLOG.txt](https://github.com/merdok/homebridge-xiaomi-fan/files/5395143/HBLOG.txt)

Thank you for your help

**Comment by merdok** [comment]
Hi,
honestly from the log i do not see any issue with the fan. All working fine! Are you sure that it is not another plugin which is causing the issue?

**Comment by h0mesmart** [comment]
I know right, it's strange. The only thing I've change recently is installing the xiaomi roborock plugin, which use miio as well. Do you think it's related ?

**Comment by merdok** [comment]
I do not know, i am not using it. You should try uninstall it and see if that fixes your issues.

**Comment by h0mesmart** [comment]
Ok I'll unistall the other plugin and see what happens

**Comment by h0mesmart** [comment]
Update:  so even after uninstalling the xiaomi roborock plugin, I still cannot control the fan via home nor hb accessories after a while. No warning, no error in the log. I still can control the fan in mi home so they are definitely online.

**Comment by merdok** [comment]
Then you need to find what is causing the issue for you. The log looks fine and the plugin is working correctly. This looks like a local issues for me so you would need to do some analyzing there...
