### ISSUE TITLE
remove 4 level switch

### ISSUE THREAD

**Issue by xd94402002** [merdok/homebridge-xiaomi-fan#63]
Wish to add the setting in config to remove the 4 level fan speed switch. 

Thank you for your help

**Comment by xd94402002** [comment]
sorry for open the issue

**Comment by merdok** [comment]
Just check the README, there it is described how you can disable them :)

**Comment by xd94402002** [comment]
Yeh. I found it just after I open the issue. 

Thanks for reply.
