### ISSUE TITLE
Problem with Mifan 2 with homebridge

### ISSUE THREAD

**Issue by DarkSyler21** [merdok/homebridge-xiaomi-fan#64]
Hi there been using your plugin for some time now with homebridge and worked perfectly recently I'm experiencing issues with plugin and the fan when using home kit.
Fan gets disconnect a lot and a very long delay after I press the accessory in the home app (when using the mi-home app works good).
example from logs:
[11/5/2020, 13:06:53] [xiaomifan] [Fan] Connected to Fan zhimi.fan.za3
[11/5/2020, 13:06:53] [xiaomifan] [Fan] Fan total use time: 67620 minutes.
[11/5/2020, 13:07:10] [xiaomifan] [Fan] Connected to Fan zhimi.fan.za3
[11/5/2020, 13:07:11] [xiaomifan] [Fan] Fan total use time: 67620 minutes.

also a lot of loading time from when restarting the server until fan is discoverable:

[11/5/2020, 13:05:47] [xiaomifan] Init - initializing devices
[11/5/2020, 13:05:47] [xiaomifan] [Fan] Init - got fan configuration, initializing device with name: Fan

(look at the time difference) more then a minute
tried to enable the deep debug mode but nothing happened.

thanks!

**Comment by merdok** [comment]
Hi,

I do not think that this is related to the plugin. It looks more like an issue with the fan, did you try reset the fan? It might also be an issue related to you network. Another cause could be that the device where you run homebridge on is on its limit, low RAM or high CPU usage do you would need to recheck that, eventually reinstall homebridge.

**Comment by DarkSyler21** [comment]
> Hi,
> 
> I do not think that this is related to the plugin. It looks more like an issue with the fan, did you try reset the fan? It might also be an issue related to you network. Another cause could be that the device where you run homebridge on is on its limit, low RAM or high CPU usage do you would need to recheck that, eventually reinstall homebridge.

Thanks for reply.
I tried resetting it and as I said it works fine with mi-home app.
I am going to change router because other issue I have but still everything else is working well on home bridge.
I’m attaching a photo of current rpi  homebridge load which I don’t think is the case
![065CAC95-0F59-44C7-ABEE-17F715A68759](https://user-images.githubusercontent.com/68989255/98273236-b3fc1980-1f9a-11eb-9e0e-a8070faf8930.jpeg)

**Comment by merdok** [comment]
RAM is slowly on the limit... 
Anyway this is most probably a local issue on your side, you would need to do some analyzing to find the root cause of your troubles. I suspect it can be one of those three things (device itself, network or the homebridge device) . Maybe also could be some homebridge cache so maybe you could try to clear that?

**Comment by DarkSyler21** [comment]
ok sure I'll try that!
make a few tests and will come with results.
thanks for the help
