### ISSUE TITLE
Problems with Setup - It doesn't appear in the HOME app

### ISSUE THREAD

**Issue by Feat44** [merdok/homebridge-xiaomi-fan#66]
Hi. I'm new to Homebridge. So far I got Hoobs working with Yeelight lamps. I installed your pluging and 
 retrieved the necessary token and so on for the Xiaomi Fan. I have the model: zhimi.fan.sa1

So far I have configured it like this: 

_{
    "platforms": [
        {
            "platform": "xiaomifan",
            "devices": [
                {
                    "name": "Mi Standing Fan",
                    "ip": "192.168.XX.XX",
                    "token": "32 Token number",
                    "pollingInterval": 10,
                    "moveControl": true,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeControl": true,
                    "shutdownTimer": true,
                    "angleButtons": [
                        5,
                        60,
                        100
                    ]
                }
            ]
        }
    ]
}_

In the section "Fan Configuration fields" of your readme you're referring to "deviceId"/miot protocol . How do I figure out which model uses the miot protocoll? 
Also for "model" do I just use "zhimi.fan.sa1" ? 
I've googled a bit but I couldn'T get it going. 
The debug says: "The devices property is not of type array. Cannot initialize. Type: object"

**Comment by merdok** [comment]
Hi,
this error usually means that something is not correct with your config. This is somehow related to HOOBS, so double check your config.
As for the the `model` property, you can leave that empty. After the first successful connection the plugin will automatically detect the model of your fan.
