### ISSUE TITLE
Mi Smart Standing Fan Pro

### ISSUE THREAD

**Issue by mszf** [merdok/homebridge-xiaomi-fan#67]
Hi, please could you add support for latest Mi Smart Standing Fan Pro, EU version (dmaker.fan.p15)?
I think there is also another one: dmaker.fan.p11, probably just because of different regions.

**Comment by merdok** [comment]
Does nothing work right now or at least something is working?

**Comment by mszf** [comment]
It is getting connected and shows up in HomeKit, but it responds only to on/off commands. Trying to use any other commands results in no response status in HomeKit and no of fan parameters is being changed.
It starts responding again after some time (maybe this time depends just on pull down times)
I added manually DID and model: dmaker.fan.p15

**Comment by merdok** [comment]
ok, i will check that out and try to add support for that fan!

**Comment by mszf** [comment]
Appreciate that, and thanks for your time spend on this 👍 If you need any help with testing, just let me know.

**Comment by merdok** [comment]
After i submit the update with the support you will need to test it :) So you say the p11 and p15 are basically the same, just for different regions?

**Comment by mszf** [comment]
Of course, will be glad to test it.

Sorry for potential confusion in topic of p11. Personally I have p15 and only saw that it should be very similar to p11. Maybe I shouldn't mention it.

**Comment by merdok** [comment]
@mszf do i see it correctly that this is a AC fan where you cannot freely control the fan speed? You can use just predefined fan levels?

**Comment by mszf** [comment]
It has 4 pre-defined levels, but when using it in Mi Home app you can still control it step less inside the range of those levels so you have whole scale to use.
In Mi Home automations it is limited only to those levels.

![image](https://user-images.githubusercontent.com/25150520/101266855-37a05600-3753-11eb-9338-69860e8ba73e.png)

![image](https://user-images.githubusercontent.com/25150520/101266858-3bcc7380-3753-11eb-99fc-ba0a17c6d05e.png)

**Comment by merdok** [comment]
Interesting because i do not see the step less control in the spec of that fan... I wonder how the mi home app controls that without a defined service... I try to guess a service for that but i i think it will not work. We would need to do some debugging with your fan and try to find how the mi home app does it...

**Comment by merdok** [comment]
@mszf please try version 1.4.4

**Comment by mszf** [comment]
Updated to v 1.4.4, restarted HomeBridge.

Switching things like led, buzzer, or natural mode works now fine :), just turning power on/off works too, but as soon I'm trying to change fan speed I get "no response" status in HomeKit.

Tested also to control it from Mi Home app and watched mirrored statuses in HomeKit and status for fan speed dosen't mirrors, just showing 0% all the time. Other statuses are updated correctly. 

Don't know if your plugin is capable of showing fan battery status but Mi Fan Pro has also a build in battery.

**Comment by merdok** [comment]
Yeah, fan speed will not work, besides setting the fan levels using the buttons which you need to enable. If you have time and are willing to do some debugging then you can come on the discord channel and we can try a couple things there. Not sure why the step less control is not in the spec but still can be done...

As of the battery, all the newer fans from xiaomi do not report the battery status anymore, so i cannot do anything about it.

**Comment by mszf** [comment]
Sure, it is worth a try, just let me know what I can do to help with this :)

**Comment by merdok** [comment]
@mszf just join the xiaomi-fan discord channel and send me a message, that will be easier and faster.

**Comment by mszf** [comment]
Can you help me with address, can't find it or doesn't know exactly which one you mean 😄

**Comment by merdok** [comment]
The link is in the README header: https://github.com/merdok/homebridge-xiaomi-fan#homebridge-xiaomi-fan

**Comment by mszf** [comment]
Thanks, missed that, now I joined and has sent you a message.

**Comment by rezmus** [comment]
you can add dmaker.fan.p8 (Mi Smart Standing Fan 1C) to the list. it's cn version of dmaker.fan.1c and works exactly same way.

**Comment by merdok** [comment]
@rezmus added in version 1.4.6!

@mszf fixed step less fan speed control in version 1.4.6
