### ISSUE TITLE
Homebridge keeps showing plugin as "out of date"

### ISSUE THREAD

**Issue by Trippersgarage** [merdok/homebridge-xiaomi-fan#68]
Just updated to the latest version you just released; 1.4.6

Strangly, home bridge keeps showing "1 plug in out of date" despite having already updated it?

Running homebridge on raspberry pi;
OS | Raspbian GNU/Linux Buster (10)
Node v14.15.1
nom v6.14.9

**Comment by merdok** [comment]
Hi,

I do not think that this has anything to do with this plugin. Probably a homebridge issue?

**Comment by Trippersgarage** [comment]
Hi Merdok.

Looks like a few reboots and some swearing sorted it out. Thank you for the speedy reply and all your work!

**Comment by merdok** [comment]
Good to hear👍 thanks for letting me know!
