### ISSUE TITLE
Swing Mode

### ISSUE THREAD

**Issue by mountbatt** [merdok/homebridge-xiaomi-fan#7]
Hi, are there any plans to add a HomeKit Switch for choosing SwingMode? (Standard / Natural)
I see get.SwingMode in index, but no config etc.

Thanks
Tobias

**Comment by merdok** [comment]
Hi, 
I think that this should be already included on the fan device itself. So there should be a swing mode on the accessory. 
Did you try that?

**Comment by ghost** [comment]
@merdok have you retrieved your fan from the basement yet? :)

**Comment by mountbatt** [comment]
You mean a Hardware Button?

**Comment by merdok** [comment]
@malmentm still too cold here :) But will do that soon!

@mountbatt no, in HomeKit the fan accessory should have a dedicated button for the swing mode.

**Comment by mountbatt** [comment]
![Screenshot 2020-05-26 13 15 41](https://user-images.githubusercontent.com/2411246/82894531-026cad00-9f53-11ea-9e9c-49dfd2d13d6e.png)
@merdok Cant find it

**Comment by merdok** [comment]
@mountbatt just open the My Xiaomi Fan accessory, there is a switch for swing. In order to change the Swing Mode you have to change the rotation (there is unfortunately no native way to do that so i put it under the rotation)

**Comment by mountbatt** [comment]
@merdok Sorry, i am absolutely new to this and again: can't find what you describe. :(

**Comment by mountbatt** [comment]
@merdok Oh … i found it :) In my screenshot i can click on the 1. item and then i can find it. nice. It was more a problem with the home-app ui and myself :)

**Comment by merdok** [comment]
Heh, no problem :) Glad that you found it 👍
