### ISSUE TITLE
Native speed switch possible?

### ISSUE THREAD

**Issue by xchris68** [merdok/homebridge-xiaomi-fan#72]
Hi, thanks for your work. I have a question: Is there a way to replace the 3 level switches with an native HomeKit speed switch(screenshot) like it is done in the Roborock Homebridge plugin for example?

![IMG_0918](https://user-images.githubusercontent.com/78270775/106362131-7ac91080-6321-11eb-8f75-b3cb9a720107.jpeg)

**Comment by merdok** [comment]
Hi,
i suppose you have the 1C fan, right? This fan only supports 3 fan levels and no step less fan control so adding a percentage slider to control 3 levels of speed would just be confusing( actually it was like that at the beginning but i adjusted it it properly display what the fan supports)

**Comment by xchris68** [comment]
Yes its the 1C, I thought it would be like in the other plugin that the device is using the level nearest to the percentage set in HomeKit. I suppose there is no simple way to change that? :)

**Comment by merdok** [comment]
It was like before, but the user experience that way is bad from my point of view and it just unnecessary confuses the user. I mean why you would want to show a slider when the fan does not support it. Even the xiaomi home app just shows the 3 level switches.

**Comment by xchris68** [comment]
It's more a visual thing for me. I'm just trying to keep HomeKit as "empty" as possible because of the "specialities" of the iOS Home app but I understand your point.

**Comment by merdok** [comment]
I agree with you that from the view point of keeping the HomeKit UI clean it would be better to have it under one control. I hope that Apple will improve that in the future and that they implement such a switch with multiple levels which could be used for that scenario...

**Comment by xchris68** [comment]
I like HomeKit but Apple has to improve many things. I hope with in future we will have only one standard like Thread and a better cleaner Home app.
