### ISSUE TITLE
how to disable "Fan total use time" in homebridge log?

### ISSUE THREAD

**Issue by cyrusauyeungc** [merdok/homebridge-xiaomi-fan#73]
Thanks for the great work and my family is enjoying a lot.
However, there is a constant message in the log counting the up time of the fan, which I think this is quite frequent and I've attached part of it for your reference. Is there a config we can use to turn off the the below log? thanks

[2/1/2021, 6:18:16 PM] [xiaomifan] [fanfan] Connected to Fan zhimi.fan.za4
[2/1/2021, 6:18:23 PM] [xiaomifan] [fanfan] Connected to Fan zhimi.fan.za4
[2/1/2021, 6:18:24 PM] [xiaomifan] [fanfan] Fan total use time: 2045 minutes.
[2/1/2021, 6:18:42 PM] [xiaomifan] [fanfan] Connected to Fan zhimi.fan.za4
[2/1/2021, 6:18:44 PM] [xiaomifan] [fanfan] Fan total use time: 2045 minutes.
[2/1/2021, 6:19:09 PM] [xiaomifan] [fanfan] Connected to Fan zhimi.fan.za4
[2/1/2021, 6:19:11 PM] [xiaomifan] [fanfan] Fan total use time: 2045 minutes.

**Comment by merdok** [comment]
Hello,
it is not possible to turn it off. I mean this is just a log message which you only see when you actually want to see the log so I do not think that this should affect anything, so I am not quite sure why this should be an issue?

**Comment by cyrusauyeungc** [comment]
I guess the frequency is too high and it's a bit overwhelming, which would sometimes pushed away the actual message from other plugins. You can see the message came in every ~10s-20s. or is there any way to make it less frequent? thanks

**Comment by merdok** [comment]
The message only comes up once when a connection to your fan is established. If you frequently disconnect your fan from electricity then it will come up and every new connect. If it comes up every 10-20 seconds then your fan does not have a stable connection and frequently reconnects.

**Comment by cyrusauyeungc** [comment]
I’ve added the “deepDebugLog": false explicitly and it resolves the issue.

**Comment by cyrusauyeungc** [comment]
Tried to do further investigation and found that the xiaomi fan is jumping between the 2 mesh satellites (which didn't happen for my other xiaomi devices), thus keeps showing the connection time message.

**Comment by merdok** [comment]
Oh, so it indeed dropped connection and reconnected frequently?
