### ISSUE TITLE
Update: Xiaomi Mijia Oscillating Fans Desk Fan With 5 Speed

### ISSUE THREAD

**Issue by calvinngkk** [merdok/homebridge-xiaomi-fan#74]
Overall this Fan can connect to the Plugins but minor update would be nice

This fan support 5 Speed (Current 4 Speed)
This fan support Oscillating Left/Right & Top Down (currently no support)
The rest of the mode all support and working fine

**Comment by merdok** [comment]
What fan model is it exactly?

**Comment by calvinngkk** [comment]
In miHome it is name : Mi Smart Air Circulator Fan
![image](https://user-images.githubusercontent.com/77764067/108345369-25459c80-7219-11eb-8a13-aef00fbc5b4c.jpeg)

**Comment by merdok** [comment]
You need to provide me with the exact model name. It should be written on the fan or in the xiaomi home app. 
Usually the model starts with zhimi or dmaker

**Comment by calvinngkk** [comment]
![image](https://user-images.githubusercontent.com/77764067/108511247-9f018700-72fa-11eb-9c08-e1fd6594f8e8.jpeg)
![image](https://user-images.githubusercontent.com/77764067/108511262-a6289500-72fa-11eb-9f47-fe761a28ae7b.png)
![image](https://user-images.githubusercontent.com/77764067/108511288-ad4fa300-72fa-11eb-8d64-6cc0db33e0e4.png)

**Comment by calvinngkk** [comment]
Mijia DC Variable Frequency Circulating Fan Desktop Product Model: ZLXHS01ZM Circulating Fan Rated Voltage: 12V = Circulating Fan Rated Power: 24W Adapter Rated Input: 100-240V~, 50/60Hz, 0.6A This equipment includes the model approval code CMIIT ID: 2017DP7231  The manufacturer of the radio transmitter module: Beijing Zhimi Electronic Technology Co., Ltd. Service Tel: 400-100-5678 200330-Y CC

**Comment by merdok** [comment]
Thanks, but you still did not give me the exact fan model... I do not know which fan model your fan is. You can also try to check the debug log from homebridge. When my plugin starts then the fan model is written in log. Also if you say that the fan is working partially with the plugin then you can simply check in Homekit, there are some device information and one of them should be the model.

**Comment by calvinngkk** [comment]
Mi Smart Air Circulator Fan
IP: 192.168.0.50

MAC: 5C:E5:0C:16:86:9E
Token: <Removed>
Model: zhimi.fan.fa1
Region: cn

**Comment by merdok** [comment]
Yes, that is the model 👍  Thanks. 
So what is  exactly not working?
- Top and Down oscillation?
- And you say that there are only 5 levels? Are you sure about that because i see in the code that i have specified 5 levels...

**Comment by calvinngkk** [comment]
At the moment
Fan speed available 1,3,3,4 (5 missing)
Oscillation angle tried not responding
Tried follow 30,60,90,120 not working

The rest is working

![image](https://user-images.githubusercontent.com/77764067/108596595-fd913880-73c0-11eb-88a1-69e22d33536d.png)

![image](https://user-images.githubusercontent.com/77764067/108596602-100b7200-73c1-11eb-8efd-d4bd6a7b93fb.png)

**Comment by merdok** [comment]
Okay, thanks for the info I will have a look at it and see what i can do!

**Comment by merdok** [comment]
@calvinngkk are you sure that your plugin is correctly configured? Or did you maybe hide/move some buttons out? I just checked and i can see all 5 levels appearing for me. 
Also do you see any error in the debug console when you try to set the oscillation angle? How do you set the oscillation angle, since i do not see any buttons for the angle in your HomeKit?

**Comment by calvinngkk** [comment]
Maybe configured wrongly here is my configuration. Pls have a look and advise
![image](https://user-images.githubusercontent.com/77764067/108785501-84eecf80-75ac-11eb-81c8-2df1c1aabb1f.png)

![image](https://user-images.githubusercontent.com/77764067/108785510-8a4c1a00-75ac-11eb-87a6-d0f66f36b59e.png)
![image](https://user-images.githubusercontent.com/77764067/108785522-9041fb00-75ac-11eb-950c-a514c5ee3235.png)

**Comment by merdok** [comment]
Hmm, looks ok. Did you try to reinstall the plugin? Maybe you do not have the latest version installed?

**Comment by calvinngkk** [comment]
![image](https://user-images.githubusercontent.com/77764067/108928689-8c31de00-767d-11eb-8938-fd53f9e6338e.png)

Reinstall the plugin,
Re add the fan,
Add device id...
Still same I'll try tonight to see whats wrong

**Comment by merdok** [comment]
Please remove the deviceId property since this is the wrong value! If you do not know the correct value then just leave it out so it will be retrieved automatically.

**Comment by calvinngkk** [comment]
Yeap did a full removal, including from cache and re-add everything now working

Weird... must have detected the fan wrongly first time

**Comment by merdok** [comment]
Ok, thanks for the info 👍
