### ISSUE TITLE
Homebridge 1.3.x warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-xiaomi-fan#75]
@merdok  I hope you are well.

With Homebridge 1.3.x I noticed the following in the Log...

[20.2.2021, 12:35:01] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

**Comment by merdok** [comment]
@Djay-X Thanks for reporting, will take care of this 👍  Can you please tell me which exactly fan do you have?

**Comment by DJay-X** [comment]
Not in use at the moment but coming again in summer. ☀️
zhimi.fan.za1

In the config at the currently
zhimi.fan.za4
dmaker.fan.p9


```
{
            "platform": "xiaomifan",
            "devices": [
                {
                    "name": "Standventilator S2",
                    "ip": "xxx.xxx.xxx.xx",
                    "token": "xxxx",
                    "model": "zhimi.fan.za4",
                    "pollingInterval": 10,
                    "moveControl": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeButton": true,
                    "shutdownTimer": false,
                    "fanLevelControl": false
                },
                {
                    "name": "Turmventilator",
                    "ip": "xxx.xxx.xxx.xx",
                    "token": "xxxx",
                    "model": "dmaker.fan.p9",
                    "pollingInterval": 10,
                    "moveControl": false,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeButton": true,
                    "shutdownTimer": false,
                    "fanLevelControl": false,
                    "angleButtons": []
                }
            ]
        },
```

**Comment by merdok** [comment]
Ok, thanks! I will check it out!

**Comment by merdok** [comment]
@DJay-X  can you tell me when does exactly the error appear? Like exact steps to reproduce to make the error appear?

**Comment by DJay-X** [comment]
I had an eye on this but can't reproduce it for whatever reason. All the fans seem to work. So I think nothing critical. 
If I notice anything in the next days again, of course I'll let you know and maybe others also facing this message in the log. 
Thanks again.

**Comment by merdok** [comment]
Okay 👍 
I tried to fix it yesterday but could not reproduce it so if it happens again please tell me when it exactly happened and I will take care of it😊

**Comment by MrMysakovich** [comment]
Hi, I have dmaker.fan.p15 and have same problem, also getting No Response Error.. What exactly you need to fix this problems?

Also speed by percent doesn't work.. only works turn on, turn off and settings level by switch.. If I press other switches, it will say No response.. 

btw when I press oscillate it doesn't work.. instead of oscillate it turns on wind mode.

also I get this: This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

I appreciate your passion to do this plugin and I am ready to help you with reproducing steps..

**Comment by merdok** [comment]
@MrMysakovich i think you should open a separate issue if something doe snot work for you. You would need to provide some debug log there with any possible error which popups during your actions.

As for the characteristic was supplied illegal value error this is the right place 😄  You should provide the steps here which you do when the error pops up so i can reproduce it.

**Comment by MrMysakovich** [comment]
@merdok When I do anything it still appears in log this: 
<img width="1040" alt="Screen Shot 2021-02-22 at 19 28 23" src="https://user-images.githubusercontent.com/20167357/108752803-3ad20380-7544-11eb-9ecd-2ec59413f43a.png">

**Comment by merdok** [comment]
@MrMysakovich seems like you had an out of date plugin version, is this warning now also resolved for you after using the latest version?

**Comment by MrMysakovich** [comment]
@merdok fixed too :-) No problems now :-)
