### ISSUE TITLE
Zhmi  Heater za2

### ISSUE THREAD

**Issue by Reddyzinho** [merdok/homebridge-xiaomi-fan#76]
Hello. 

Is it possible to create a connection to zhmi.heater.za2 from smartMI with this plugin? Can you add this option?

**Comment by merdok** [comment]
Hi,
unfortunately adding heater support to this plugin does not make any sense since this is a fan plugin. But I am working on another plugin and including heaters there should be possible, i just do not know when i will be able to finish it and release it so just keep an eye on my profile 😉

**Comment by Reddyzinho** [comment]
Thanks a lot for your fast answer and kindness.  I have seen a plugin there for heaters, but the type of the accessory is a “sensor” and not a FAN, and can’t control anything there, only ON and OFF :/ 
I think this can be a FAN.....but with hot air ;))))) But i will wait for your plugin. 
Once more, thanks again for your efforts :) 

Hug from Portugal

**Comment by merdok** [comment]
@Reddyzinho 
you can now try the new plugin https://www.npmjs.com/package/homebridge-miot
Please let me know if everything works

**Comment by Reddyzinho** [comment]
Hi there. 
Thanks a lot for your kind and fast version including this equipment. 
unfortunately I have errors here. I have updated to latest version of homebridge once your plugin only accept the new version (v13). Then erros occurs with my installations and with your plugin. See the image below
Enter in a kind of a loop ....and this messages appears indefinitely on time ...and the heater appear at HomeKit but without any working button. 

![19A94CAF-5A12-441C-876F-1D5A498F917D](https://user-images.githubusercontent.com/3985096/109645451-c0f6d700-7b4e-11eb-853c-cec67cdc77c3.png)

**Comment by merdok** [comment]
Thanks for the report.
Can you please post a debug log? You would need to start homebridge in debug mode to do that.

**Comment by Reddyzinho** [comment]
I will do that but can you allow this plugin to roll on a lower version of homebridge ? :( I have upgraded and my garage door doesn’t work and some of my IR equipments as well and have to do all again ;(((( 


Atentamente,

Tiago Cunha

No dia 02/03/2021, às 12:10, Marcin <notifications@github.com> escreveu:

﻿
Thanks for the report.
Can you please post a debug log? You would need to start homebridge in debug mode to do that.

**Comment by merdok** [comment]
I will check it out if I can do it, for now please provide me with the debug log so I can see what the issue is.

**Comment by Reddyzinho** [comment]
Hello

I get this with homebridge -D

[02/03/2021, 15:16:46] [miot] [Miot device] Doing device specific setup
[02/03/2021, 15:16:46] [miot] [Miot device] Doing initial properties fetch
[02/03/2021, 15:16:46] [miot] [Miot device] Device setup finished! Device ready, you can now control your device!
[02/03/2021, 15:16:46] [miot] [Miot device] Device connected!
[02/03/2021, 15:16:46] [miot] [Miot device] TypeError: this.miotDevice.getFanModel is not a function
[02/03/2021, 15:16:46] [miot] [Miot device] Could not connect to the device! Retrying in 30 seconds!
[02/03/2021, 15:16:46] [miot] [Miot device] Error on initial property request! ReferenceError: siid is not defined



Atentamente,

Tiago Cunha

No dia 02/03/2021, às 14:11, Marcin <notifications@github.com> escreveu:

﻿
I will check it out if I can do it, for now please provide me with the debug log so I can see what the issue is.

**Comment by merdok** [comment]
Thanks. That is helpful! I will try to fix the issues and will let you know!

**Comment by Reddyzinho** [comment]
Thanks :)) 


Atentamente,

Tiago Cunha

No dia 02/03/2021, às 15:28, Marcin <notifications@github.com> escreveu:

﻿
Thanks. That is helpful! I will try to fix the issues and will let you know!

**Comment by merdok** [comment]
Ok, i just submitted version 0.3.1. Please try now. That should hopefully fix your issue.

**Comment by Reddyzinho** [comment]
And you can allow to inferior version ? V12.2.4? 

Because if I install your plugin I can’t use the other ones :( 


Atentamente,

Tiago Cunha

No dia 02/03/2021, às 16:26, Marcin <notifications@github.com> escreveu:

﻿
Ok, i just submitted version 0.3.1. Please try now. That should hopefully fix your issue.

**Comment by merdok** [comment]
This is a bigger work which needs to be done, first i need to fix the core issues. So i hope that the 0.3.1 version will now work.

**Comment by Reddyzinho** [comment]
Ok thanks a lot friend. 


Atentamente,

Tiago Cunha

No dia 02/03/2021, às 16:55, Marcin <notifications@github.com> escreveu:

﻿
This is a bigger work which needs to be done, first i need to fix the core issues. So i hope that the 0.3.1 version will now work.

**Comment by merdok** [comment]
@Reddyzinho so did you check if it works after the update?

**Comment by Reddyzinho** [comment]
At the moment no. But I will do soon. I will post here


Atentamente,

Tiago Cunha

No dia 02/03/2021, às 17:13, Marcin <notifications@github.com> escreveu:

﻿
@Reddyzinho so did you check if it works after the update?

**Comment by merdok** [comment]
Ok, thanks!
