### ISSUE TITLE
Issues with Mi Smart Standing Fan Pro

### ISSUE THREAD

**Issue by MrMysakovich** [merdok/homebridge-xiaomi-fan#77]
Hi, 

so I want report some problems. 

Turning on/off works correctly. 

Slider for rotation speed is not working. 

Buttons for levels working correctly. 

Oscillate works as Natural/Direct switch so Oscillate is not working as expected. 

Turning on and off beeps working properly. 

Shutdown timer is not working. 

Natural mode is not working.

Move left/right is not appearing in HK. 

Led Control is not working. 

Only this I get when I trying what doesn't work.

<img width="1040" alt="Screen Shot 2021-02-22 at 19 28 23" src="https://user-images.githubusercontent.com/20167357/108753462-0f034d80-7545-11eb-98f6-5a26b1fbb0ee.png">

**Comment by merdok** [comment]
@MrMysakovich what model is your?  Could you also post your config?
Please enable deep debug log: https://github.com/merdok/homebridge-xiaomi-fan#troubleshooting and let me know what the output is when you try to run commands which are not working and also when the above error comes up.

**Comment by MrMysakovich** [comment]
@merdok Here:

<img width="523" alt="Screen Shot 2021-02-22 at 20 27 11" src="https://user-images.githubusercontent.com/20167357/108759280-71138100-754c-11eb-9aa9-94c81aabd796.png">

You can also see here model.

**Comment by MrMysakovich** [comment]
When I try slider for speed, it gives me only this: 
<img width="892" alt="Screen Shot 2021-02-22 at 20 32 13" src="https://user-images.githubusercontent.com/20167357/108759773-1a5a7700-754d-11eb-9543-f68a2c6d6690.png">

**Comment by merdok** [comment]
@MrMysakovich remove the `deviceId` property from your config, this is the wrong value which you entered there. You can use the `model` property to enter your model there.

**Comment by MrMysakovich** [comment]
@merdok I did it now and tested all features. All problems from post above exists.

**Comment by merdok** [comment]
@MrMysakovich then again, you need to enable deepDebugLog and try to control the fan, the console should give detailed info about what is happening and you need to post it here.

**Comment by MrMysakovich** [comment]
@merdok Tried and only get still same message as in first post..

**Comment by merdok** [comment]
Pretty much impossible that you only getting the message from above when you followed the instruction from the link above, you are doing something wrong. Are you sure you are starting homebridge in debug mode?

**Comment by MrMysakovich** [comment]
@merdok <img width="1059" alt="Screen Shot 2021-02-22 at 21 09 16" src="https://user-images.githubusercontent.com/20167357/108763916-3ad90000-7552-11eb-8e5d-1161292d281c.png">
This I got when adjusting speed with slider.

Sorry I was starting Debug mode only in terminal :D

**Comment by MrMysakovich** [comment]
<img width="1069" alt="Screen Shot 2021-02-22 at 21 15 29" src="https://user-images.githubusercontent.com/20167357/108764596-19c4df00-7553-11eb-81e3-17bca14bb4ce.png">
This is what I get when trying Turn On/Off LED status.

<img width="1057" alt="Screen Shot 2021-02-22 at 21 16 41" src="https://user-images.githubusercontent.com/20167357/108764759-50025e80-7553-11eb-8e3b-581d80bf43d0.png">
This is for timer.

<img width="1055" alt="Screen Shot 2021-02-22 at 21 17 55" src="https://user-images.githubusercontent.com/20167357/108764900-70cab400-7553-11eb-83d0-60228c0e9eea.png">
For natural mode.

Move control doesn't appear in HomeKit. 

When I press this, nothing shows in log..
![image](https://user-images.githubusercontent.com/20167357/108765245-d3bc4b00-7553-11eb-8d27-dff28d362343.png)


<img width="1052" alt="Screen Shot 2021-02-22 at 21 21 37" src="https://user-images.githubusercontent.com/20167357/108765353-f484a080-7553-11eb-8a24-aaaf89976dcf.png">

This appear when I want to Oscillate. But instead of oscillate it sets natural mode.

<img width="1053" alt="Screen Shot 2021-02-22 at 21 24 19" src="https://user-images.githubusercontent.com/20167357/108765684-64932680-7554-11eb-9544-109283c72b55.png">

This shows when trying child lock, but it doesn't lock buttons...

**Comment by merdok** [comment]
Are you sure that your fan model is the `dmaker.fan.p15`? If your are unsure then the best is that you delete this from the config. Also try to reset your fan, it might be that it got stuck and does not respond correctly to some command anymore.

**Comment by MrMysakovich** [comment]
@merdok I get this dmaker.fan.p15 from Get_MiHome_devices_token app.

**Comment by merdok** [comment]
@MrMysakovich something is not right with your fan configuration. Can you post the log when you start homerbidge, at some point the plugin will initialize and there will be some debug log.

**Comment by MrMysakovich** [comment]
@merdok Wow, everything works after remove and new installation of plugin, but oscillation doesn't work when I press this button: 

![](https://user-images.githubusercontent.com/20167357/108765245-d3bc4b00-7553-11eb-8d27-dff28d362343.png)

**Comment by merdok** [comment]
@MrMysakovich this is not a button for oscillation. This is the direction button and it has no function on xiaomi fans since the direction cannot be controlled. The oscillation button is hidden on the fan accessory.

**Comment by MrMysakovich** [comment]
@merdok Ohh good to know that thankkkss :-) and only what I now find out is when I press for example angle 120, it goes to 120 degrees but it turns on oscillation.

**Comment by MrMysakovich** [comment]
What the hell maaan, now I understand all of features and all is working as expected. Angle 120 is for oscillation.. you are pure genius :-)

**Comment by merdok** [comment]
That is good :) So can this be closed?

**Comment by MrMysakovich** [comment]
Yes of course :-)
