### ISSUE TITLE
Swing Mode on not working

### ISSUE THREAD

**Issue by DanialMaude** [merdok/homebridge-xiaomi-fan#78]
Hello everyone, im hoping someone can help me. I have home bridge installed on a 2017 Macpro. I had an issue with my Mac A few weeks ago, as such I reset home bridge completely. Having done so, when I ask Siri (home pods, iPhone and Mac) to turn sing mode off. Nothing happens?! I know home bridge is sending instructions to the fan as its lights up. However, the fan does not oscillate. My config is no different to what it was the first time I set it up. However, when I set it up first everything worked. Anyone got any suggestions?

**Comment by merdok** [comment]
Maybe your token changed? You could also post here some debug log so I can have a look what is happening under the hood.

**Comment by MrMysakovich** [comment]
Hi, can confirm same problem. Everything works except Hey Siri turn on swing mode. Siri says Swing mode is ON, but nothing happens. When I press oscillate in HomeKit, it is working flawlessly.

**Comment by MrMysakovich** [comment]
@DanialMaude please can you send logs to author of this plugin? I am not at home for week, so can’t send it.
