### ISSUE TITLE
希望下个版本可以修改图标

### ISSUE THREAD

**Issue by ariakeumi** [merdok/homebridge-xiaomi-fan#79]
![image](https://user-images.githubusercontent.com/13041855/110102053-44c6f280-7ddf-11eb-935f-e158bc5c474b.png)

**Comment by DJay-X** [comment]
Oh wow. You are right. In Home App you can't change the Fan icon. Because I use Eve App most of the time I never noticed. But of course it would be great if @merdok finds a way to make this possible in a next update. 👍

**Comment by merdok** [comment]
If this is about the icon change, I do not think that there is anything I can do about it. I am not really sure how it is decided what icons to show, I already mark the accessory as a fan so it should actually be possible.

**Comment by ariakeumi** [comment]
> If this is about the icon change, I do not think that there is anything I can do about it. I am not really sure how it is decided what icons to show, I already mark the accessory as a fan so it should actually be possible.

thank u

**Comment by merdok** [comment]
BTW, if you have a miot fan device, you can try my new plugin https://github.com/merdok/homebridge-miot

The fans are slightly different implemented there so if it has something to do with the implementation then it might be that it works there.
