### ISSUE TITLE
Smartmi Standing Fan 2 shows "no response" or turned off even when on & running

### ISSUE THREAD

**Issue by balajim212** [merdok/homebridge-xiaomi-fan#85]
I have this model zhimi.fan.za3 (Smartmi Standing Fan 2) added via this plugin, but even though the fan is on & running in the Mi Home app, it shows off & no updated status in the Apple Home app.
Tried reinstalling the plugin multiple times & also restarting HomeBridge, no luck. Other Mi devices like Roborock vacuum & Air purifier pro work just fine.
It has a DHCP reserved IP so doesn't change, also token is extracted correctly from the Windows "get MI token app". Attaching the screenshots from both apps.
What might be the issue?

![Mi app](https://user-images.githubusercontent.com/73424816/117104869-f1950000-ad8d-11eb-8e7f-b8c444b8e844.jpeg)
![Home app](https://user-images.githubusercontent.com/73424816/117104877-f5c11d80-ad8d-11eb-9e89-e40919e1eb77.jpeg)

**Comment by merdok** [comment]
My guess is either the ip or token you provided are wrong. 

You can try to start homebridge in debug mode and post the output here so we can check what is exactly happening there.
