### ISSUE TITLE
Disconnection issue with SmartMI 2S Fan

### ISSUE THREAD

**Issue by xToken** [merdok/homebridge-xiaomi-fan#86]
I have an issue where my smartmi 2S fan will disconnect randomly after a couple hours and never reconnect.  If I restart homebridge then the fan will reconnect right away and start working again.  I tried enabling the debug mode for the plugin but wasnt able to spot any issues readily in the logs.  Below is an except of what I typically see in the logs when this happens:

```
[5/14/2021, 3:06:07 AM] [xiaomifan] [Bedroom Fan] Updated properties: 
 {
  "angle": 120,
  "speed": 397,
  "poweroff_time": 0,
  "power": "on",
  "ac_power": "on",
  "angle_enable": "off",
  "speed_level": 20,
  "natural_level": 0,
  "child_lock": "off",
  "buzzer": 0,
  "led_b": 1,
  "use_time": 3850
}
[5/14/2021, 3:06:12 AM] [xiaomifan] [Bedroom Fan] Updated properties: 
 {
  "angle": 120,
  "speed": 398,
  "poweroff_time": 0,
  "power": "on",
  "ac_power": "on",
  "angle_enable": "off",
  "speed_level": 20,
  "natural_level": 0,
  "child_lock": "off",
  "buzzer": 0,
  "led_b": 1,
  "use_time": 3850
}
[5/14/2021, 3:06:28 AM] [xiaomifan] [Bedroom Fan] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out
[5/14/2021, 3:06:28 AM] [xiaomifan] [Bedroom Fan] Trying to reconnect
[5/14/2021, 3:06:40 AM] [xiaomifan] [Bedroom Fan] Error: Could not connect to device, token might be wrong
[5/14/2021, 3:06:40 AM] [xiaomifan] [Bedroom Fan] Could not connect to the fan! Retrying in 30 seconds!
```

Once the issue happens the last 2 lines will repeat.

**Comment by merdok** [comment]
I also have s SmartMi Fan2S and did not observe such issue. Can you still ping the fan manually? If you leave it like that will never reconnect again?

**Comment by xToken** [comment]
I can still ping the fan from the ubuntu VM, but it will never connect to homebridge again until I restart homebridge (and then it comes right back up)

One note is that my homebridge VM has 2 network adapters connected to 2 different VLANs.

**Comment by merdok** [comment]
Strange, no idea why this happening in your case. Is your homebridge installation and all your plugins up to date?

**Comment by xToken** [comment]
Homebridge and all plugins were up to date - I tried updating nodeJS but that didnt help.
When testing the fans response via pings I noticed that the response times varied a lot - from 20ms to 500+ms.. Looking in https://github.com/aholstenson/miio/blob/master/lib/network.js it looks like the default handshake timeout is 2000ms.. I increased that to 10000 and it does seem to stay connected now - If that proves stable I will try lower values but I dont think there is any issue with your plugin atleast.

**Comment by merdok** [comment]
I think this is somehow related to your network that the response varies that much. Anyway, I think maybe it would make sense to make it configurable straight from my plugin or at least increase that. Did you right now modify the network.js file to increase the timeout?

Oh, well it is not configurable in that library which is a shame, so i guess you modified the file?

**Comment by xToken** [comment]
Yea I had modified that file directly - i tested latency to other wireless devices on my network and the latency was consistent and under 10ms - the fan is close to the edge from a range standpoint so maybe its because of that.

**Comment by merdok** [comment]
Ok 👍 I think this can be closed now!
