### ISSUE TITLE
token get changed regularly, is there any method to prevent it?

### ISSUE THREAD

**Issue by pb29** [merdok/homebridge-xiaomi-fan#87]
I think token gets changed like every two weeks? not sure about the period.
it also even unable to remote with the Mi Home app. so i have to remove and pairing my fan again with Mi Home app.
even fan gets plugged on always! is this normal? token gets changed but ip is still the same by the way.
also I get tokens with old version of android Mi home app.
my fan model is zhimi.fan.za5 (Smartmi Standing Fan 3)

**Comment by merdok** [comment]
The token should not change until you reset your device. For all my devices I just fetched the token once and never had to do it again(some more then 2 years)

I guess something is not right with your device if the token resets constantly...
