### ISSUE TITLE
Problem Set a shutdown timer :

### ISSUE THREAD

**Issue by Stewart06** [merdok/homebridge-xiaomi-fan#89]
Bonjour,

Avant tout je vous remercie pour le super travail qui a été fait pour se plugin.

J'aurai juste une suggestion concernant le minuteur.

Quand celui-ci est actif et qu'on arrête soi-même le ventilateur "modèle dmaker.fan.1c" le minuteur d'arrêt reste encore actif et figé. Cela serai top si il pouvait se réinitialiser tout seul sans devoir créer une automatisation dans HomeKit pour palier à se problème.

Merci d'avance.

Hello,

First of all, thank you for the great job that has been done for this plugin.

I will just have a suggestion regarding the timer.

When this is active and you stop the fan "model dmaker.fan.1c" yourself, the stop timer remains active and frozen. It would be great if it could reset itself without having to create an automation in HomeKit to overcome this problem.

Thank you in advance.

**Comment by Stewart06** [comment]
Bon apparement cela venait d'un problème sur mon iPhone, car je viens de m'apercevoir que cette fonction est déjà en place.

Well apparently this was due to a problem on my iPhone, because I just noticed that this function is already in place.

**Comment by merdok** [comment]
Hello,

so does it work now correctly for you? 
As long as the timer is active it will be displayed in HomeKit. Turning off the device manually before the timer runs out should actually reset the timer itself which will be reflected in HomeKit.

**Comment by Stewart06** [comment]
Affirmatif cela fonctionne parfaitement après plusieurs test que j'ai effectué. Cela venait de mon iPad qui n'actualisé pas a force de jouer avec.

Encore merci !

Affirmative it works perfectly after several tests that I have carried out. It came from my iPad which did not update by dint of playing with it.

Thanks again !
