### ISSUE TITLE
Add thing to control for oscillating angle

### ISSUE THREAD

**Issue by Km81** [merdok/homebridge-xiaomi-fan#9]
First of all, thank you for present this home bridge.

I am using the Xiaomi fan of 2s and first model.

Is it possible to add separate fan accessory in order to control oscillating angle?

For example, if the swing mode of the related fan is on, this fan accessory will be on and after checking the oscillating angle, the number of angle will be fan speed. 
(30 degree - 30, 60 degree - 60, 90 degree - 90, 120 degree - 100)

And to control the oscillating angle, if the fan speed of this new fan accessory is changed, the oscillating angle will be changed as following,
(1 ~ 30 : 30 degree, 31 ~ 60 : 60 degree, 61 ~ 90 : 90 degree, 91 ~ 100 : 120 degree)

Please consider it.

**Comment by merdok** [comment]
Hi,

You can already enable/disable the oscillation of the fan. Also you can swing your fan manually left and right by 5 degree using the moveControl property.

I do not think that knowing the current angle would be of any benefit that is why I did not add that information.

**Comment by lorenzhs** [comment]
I think you misunderstood what @Km81 meant. The Xiaomi Home app supports four different oscillation modes, where the fan swings either 30°, 60°, 90° or 120°. The setting controls how wide it swings before turning back. Apparently the property is called `oscillation_angle`: https://github.com/syssi/xiaomi_fan/blob/8b0c1f034b82667fdec0c02e0238f0c7c528555b/custom_components/xiaomi_miio_fan/fan.py#L183

**Comment by merdok** [comment]
Oh, right! I think I will add a button for each of those modes so the user can select one of them. I think a slider (light bulb) is to confusing .

**Comment by merdok** [comment]
This is now added in version 1.0.0. You can create buttons with whatever angles you wish :)
