### ISSUE TITLE
HomeKit fan icons unavailable

### ISSUE THREAD

**Issue by ojoaosemtil** [merdok/homebridge-xiaomi-fan#92]
Hello!
I can’t change the icon of the fan (currently in HomeKit you can choose from the standard fan, a tall fan and a ceiling fan).
Is it possible to be able to choose from the three different icons?

Thanks in advance!

**Comment by merdok** [comment]
Hi,
i know what you mean and I am aware of this. But I am not sure why it is not possible to select between the different icons. Also I am not quite sure if this is something that I am able to adjust or fix...
Anyway I will have a look it and will let you if I can find a solution for this!

**Comment by ojoaosemtil** [comment]
Oh I understand, maybe it is a HomeKit limitation for some reason.
Thank you!

**Comment by merdok** [comment]
Ok, i found out that the icon switching is only available on the older Fan v1 accessory from Homekit. This plugin uses the new Fan v2 accessory which generally has more features (like SwingMode) but for some reason misses the icon selection. No idea why Apple did not included that in the Fan v2 accessory...
