### ISSUE TITLE
Modification du Comportement du Plugin :

### ISSUE THREAD

**Issue by Stewart06** [merdok/homebridge-xiaomi-fan#94]
Bonjour,

Est-ce possible de modifier le comportement du plugin afin de gérer la vitesse de rotation du ventilateur.

Actuellement ce sont des interrupteurs qui interagissent pour faire varier entre les trois modes de vitesse disponible.

N’est-il pas possible de faire cela comme avec le plugin Dyson Cool qui fait varier la vitesse comme quand on varie l’intensité d’une ampoule, car cela est bien plus pratique au quotidien je vous avoue.

Voici des captures d’écran du plugin Dyson:

Hello,

  Is it possible to modify the behavior of the plugin in order to manage the fan rotation speed.

  Currently, these are switches that interact to vary the three speed modes available.

  Isn't it possible to do this like with the Dyson Cool plugin which varies the speed like when you vary the intensity of a bulb, because it is much more practical on a daily basis I admit.

  Here are screenshots of the Dyson plugin:

**Comment by Stewart06** [comment]
![IMG_0917](https://user-images.githubusercontent.com/63004191/122459311-139ab880-cfb1-11eb-8aa9-c7907213af0a.PNG)

**Comment by Stewart06** [comment]
![IMG_0918](https://user-images.githubusercontent.com/63004191/122459368-26ad8880-cfb1-11eb-9a05-1eac1029d108.PNG)

**Comment by merdok** [comment]
Hi,

it would be good if you could also post the fan model which you are using so at least i am aware of that :) Generally speaking I suppose that your device does not support steeples fan speed, that is why you do not see it. This only appears on devices which support that. If you have a miot device then you might want to try my other plugin: https://github.com/merdok/homebridge-miot there i try to emulate steeples fan speed control on device which does not support it.

**Comment by Stewart06** [comment]
Je possède le ventilateur Mi Fan 1C.

I own the Mi Fan 1C fan.

**Comment by merdok** [comment]
This is a miot device, i would recommend that you try the other plugin in that case, where fan rotation speed is emulated :)

**Comment by Stewart06** [comment]
Ok thanks I will test, because I currently have too much configuration on my fans and not the motivation to do it all again.

**Comment by merdok** [comment]
Ok, for now lets close this ticket then.
