### ISSUE TITLE
No reconnect

### ISSUE THREAD

**Issue by haukee** [merdok/homebridge-xiaomi-fan#95]
When I start up my homebridge I can control my fan. 

But when the fan is disconnected from power / goes to deep sleep and then I reconnect it, it won’t show up in home kit again. 

Controls via Xiaomi app works, so it’s not an WiFi issue. 

After I restart homebridge it works again. 

Model: zhimi.fan.za4

**Comment by merdok** [comment]
It would be good if you could reproduce the issue with homebridge running in debug mode and then post the debug log here. After that I can have look into the log and see what might be the issue.
