### ISSUE TITLE
could you pls add support to original Dream Maker Fan

### ISSUE THREAD

**Issue by danielwaw** [merdok/homebridge-xiaomi-fan#98]
Hi Merdok, I've hold two Dream Maker Fan which are same manufacturer as dmaker.p5-p15, while they're smart fans supported by Dream Maker (the manufacturer) through 造梦者+ APP and they could be connected to miot through Mi home app "other platform devices:. Could you pls add support for them? The link below maybe the miot description of Dream Maker Fan. Many thanks.

https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-02:1

**Comment by merdok** [comment]
Should be possible. What is the exact model name of the fan?

**Comment by danielwaw** [comment]
> Should be possible. What is the exact model name of the fan?

It is fan02 showed in the Dreammaker + App. The fan can be controlled by Xiaomi Xiaoai AI through the path as the picture attached below.
![dream maker connect to Xiaomi](https://user-images.githubusercontent.com/86812283/124243687-b9712a00-db50-11eb-9a7c-1be270b375ed.jpg)

**Comment by merdok** [comment]
fan02 is not the full model name! You need to provide me the full model name of your fan. If you have the token then you might try to add it to the plugin already and enable homebridge debug log. It should then show you the model name in the terminal.

**Comment by danielwaw** [comment]
> fan02 is not the full model name! You need to provide me the full model name of your fan. If you have the token then you might try to add it to the plugin already and enable homebridge debug log. It should then show you the model name in the terminal.

The Dream Maker fan is supported by the manufacturer not Xiaomi actually, so I do not have a token. It may be base on different hardware and firmware from the fans supported directly by Xiaomi smart. Thanks.

**Comment by merdok** [comment]
First off you need a token for your fan as described in the README or you will not be able to control it.
Second I need the full model name of your fan so I can add support for it!
