### ISSUE TITLE
dmaker.fan.p5 (Mi Smart Standing Fan 1X) issues

### ISSUE THREAD

**Issue by withcking** [merdok/homebridge-xiaomi-fan#99]
hello sir,
found two issues in dmaker.fan.p5 (Mi Smart Standing Fan 1X) that you maybe able to fix,
- first is oscillation angle range can be up to 140 not 120 as in the code, which causing no response when turning it on
- second is rotation direction is not supported for this fan but it was enabled on the code for this which causes the button to appear and causes the fan to have no response return on homekit

Can't provide a debug log since homebridge cannot catch the error on the rotation direction even when debug mode is turned on. I did try to force it in config to set to false but it is not detected.

**Comment by merdok** [comment]
Hi,

I will adjust the angle range.
As for the rotation direction, this button has no use on your fan, you can simply ignore it. I once removed the button so many people started to complain that the ui is broken and rearranged so I put it back in so that the the switches do not rearrange...

Greets

**Comment by withcking** [comment]
oh I see. Is it possible if we can have a switch to enable or disable it in the config? since when you accidentally press it, it causes a no response to the whole fan.
many thanks!

**Comment by merdok** [comment]
Yes, the no response is an issue which i will fix, but could you please provide me a homebridge debug log ideally with the "deepDebugLog" property set to true. It should show from where the error originates so that i can fix it.

**Comment by withcking** [comment]
Tried turning on debug mode as well as the deepDebugLog but its not raising any issues in homebridge logs.
My guess here is that it is a missing variable with a ui element which causes the no response whenever the button is touched or hovered on to.

Here's the log that's being repeated on homebridge whenever button is active -
It just repeats the values, possibly looking for the rotationdirection option to have any response.

[7/9/2021, 11:43:00 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:03 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:06 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:09 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:12 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:15 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:18 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:21 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:24 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:27 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:30 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:33 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}
[7/9/2021, 11:43:37 PM] [xiaomifan] [Fan] Updated properties: 
 {
  "power": true,
  "mode": "nature",
  "speed": 100,
  "roll_enable": true,
  "roll_angle": 140,
  "time_off": 0,
  "light": true,
  "beep_sound": true,
  "child_lock": false
}

**Comment by withcking** [comment]
If there's any other way to get other versions of the log, maybe you can direct me where?

**Comment by merdok** [comment]
Ah, i see the issue now. Will fix that in the next update!

**Comment by withcking** [comment]
Thank you!

**Comment by merdok** [comment]
Should be fixed in version 1.5.4
